package generatedcheck

import (
	"errors"
	"strings"
	"testing"

	"github.com/ronhuafeng/llm-go/codexsdk/internal/protocolgen"
)

func TestGenerateSDKSurfaceRendersExactFacade(t *testing.T) {
	manifest := protocolgen.Manifest{
		Entries: []protocolgen.ManifestEntry{{
			Direction:             "client_to_server",
			Kind:                  "request",
			Method:                "thread/start",
			FacadeTarget:          "Threads().Start",
			FacadeStatus:          "generated",
			ParamsOrPayloadSchema: "ThreadStartParams",
			ResponseType:          "ThreadStartResponse",
			Family:                "thread",
			Stability:             "stable",
		}},
	}
	got, err := GenerateSDKSurface(manifest, map[string]string{"thread/start": "MethodThreadStart"}, map[string]bool{"ThreadStartParams": true, "ThreadStartResponse": true})
	if err != nil {
		t.Fatal(err)
	}
	text := string(got)
	for _, want := range []string{
		"// Code generated by generatedcheck; DO NOT EDIT.",
		"func (c *Client) Threads() Threads",
		"func (f Threads) Start(ctx context.Context, params protocolv2.ThreadStartParams) (protocolv2.ThreadStartResponse, error)",
		"protocolv2.MethodThreadStart",
	} {
		if !strings.Contains(text, want) {
			t.Fatalf("generated surface missing %q:\n%s", want, text)
		}
	}
}

func TestGenerateSDKSurfaceIgnoresHistoricalDeferredStatusWhenPrerequisitesExist(t *testing.T) {
	manifest := protocolgen.Manifest{
		Entries: []protocolgen.ManifestEntry{{
			Direction:             "client_to_server",
			Kind:                  "request",
			Method:                "account/usage/read",
			FacadeTarget:          "Accounts().UsageRead",
			FacadeStatus:          "deferred_missing_generated_types",
			ParamsOrPayloadSchema: "GetAccountTokenUsageParams",
			ResponseSchema:        "GetAccountTokenUsageResponse.json",
			ResponseType:          "GetAccountTokenUsageResponse",
			Family:                "account",
			Stability:             "stable",
		}},
	}
	got, err := GenerateSDKSurface(
		manifest,
		map[string]string{"account/usage/read": "MethodAccountUsageRead"},
		map[string]bool{"GetAccountTokenUsageParams": true, "GetAccountTokenUsageResponse": true},
	)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(got), "func (f Accounts) UsageRead(") {
		t.Fatalf("current prerequisites must generate facade regardless of historical status:\n%s", got)
	}
}

func TestGenerateSDKSurfaceFailsClosedWhenCurrentPrerequisitesAreMissing(t *testing.T) {
	manifest := protocolgen.Manifest{
		Entries: []protocolgen.ManifestEntry{{
			Direction:             "client_to_server",
			Kind:                  "request",
			Method:                "account/usage/read",
			FacadeTarget:          "Accounts().UsageRead",
			FacadeStatus:          "deferred_missing_generated_types",
			ParamsOrPayloadSchema: "GetAccountTokenUsageParams",
			ResponseSchema:        "GetAccountTokenUsageResponse.json",
			ResponseType:          "GetAccountTokenUsageResponse",
			Family:                "account",
			Stability:             "stable",
		}},
	}
	_, err := GenerateSDKSurface(
		manifest,
		map[string]string{"account/usage/read": "MethodAccountUsageRead"},
		map[string]bool{"GetAccountTokenUsageParams": true},
	)
	var unsupported *protocolgen.UnsupportedSchemaError
	if !errors.As(err, &unsupported) || unsupported.Path != "GetAccountTokenUsageResponse.json" || !strings.Contains(unsupported.Error(), "response type GetAccountTokenUsageResponse") {
		t.Fatalf("missing prerequisite error = %v", err)
	}
}
func TestGenerateSDKSurfaceRejectsMissingGeneratedType(t *testing.T) {
	manifest := protocolgen.Manifest{
		Entries: []protocolgen.ManifestEntry{{
			Direction:             "client_to_server",
			Kind:                  "request",
			Method:                "thread/start",
			FacadeTarget:          "Threads().Start",
			FacadeStatus:          "generated",
			ParamsOrPayloadSchema: "ThreadStartParams",
			ResponseType:          "ThreadStartResponse",
			Family:                "thread",
			Stability:             "stable",
		}},
	}
	_, err := GenerateSDKSurface(manifest, map[string]string{"thread/start": "MethodThreadStart"}, map[string]bool{"ThreadStartParams": true})
	if err == nil || !strings.Contains(err.Error(), "response type ThreadStartResponse") {
		t.Fatalf("missing response type error = %v", err)
	}
}

func TestGenerateSDKSurfaceClassifiesFacadeNameCollision(t *testing.T) {
	entries := []protocolgen.ManifestEntry{}
	for _, method := range []string{"fuzzyFileSearch", "fuzzyFileSearch/search"} {
		entries = append(entries, protocolgen.ManifestEntry{
			Direction: "client_to_server", Kind: "request", Method: method,
			FacadeTarget: "FuzzyFileSearch().Search", SourceSchema: "ClientRequest.json",
			ParamsOrPayloadSchema: "SearchParams", ResponseSchema: "SearchResponse.json", ResponseType: "SearchResponse",
		})
	}
	_, err := GenerateSDKSurface(protocolgen.Manifest{Entries: entries},
		map[string]string{"fuzzyFileSearch": "MethodFuzzyFileSearch", "fuzzyFileSearch/search": "MethodFuzzyFileSearchSearch"},
		map[string]bool{"SearchParams": true, "SearchResponse": true})
	var unsupported *protocolgen.UnsupportedSchemaError
	if !errors.As(err, &unsupported) || unsupported.Path != "ClientRequest.json" || !strings.Contains(unsupported.Error(), "both \"fuzzyFileSearch\" and \"fuzzyFileSearch/search\"") {
		t.Fatalf("collision = %v, want typed source-linked incompatibility", err)
	}
}
