// Code generated by protocolv2gen; DO NOT EDIT.
package protocolv2

var ExperimentalJSONFields = map[string]map[string]struct{}{
	"BedrockAwsProfile": {
		"name":   {},
		"region": {},
	},
	"BedrockDiscoverResponse": {
		"environmentCredentials": {},
		"profiles":               {},
	},
	"BedrockEnvironmentCredential": {
		"region": {},
		"type":   {},
	},
	"BedrockSetupParamsEnvironment": {
		"region": {},
	},
	"BedrockSetupParamsProfile": {
		"profile": {},
		"region":  {},
	},
	"ClientRequestAccountBedrockDiscover": {
		"id":     {},
		"params": {},
	},
	"ClientRequestAccountBedrockSetup": {
		"id":     {},
		"params": {},
	},
	"ClientRequestCollaborationModeList": {
		"id":     {},
		"params": {},
	},
	"ClientRequestEnvironmentAdd": {
		"id":     {},
		"params": {},
	},
	"ClientRequestEnvironmentInfo": {
		"id":     {},
		"params": {},
	},
	"ClientRequestEnvironmentStatus": {
		"id":     {},
		"params": {},
	},
	"ClientRequestFuzzyFileSearchSessionStart": {
		"id":     {},
		"params": {},
	},
	"ClientRequestFuzzyFileSearchSessionStop": {
		"id":     {},
		"params": {},
	},
	"ClientRequestFuzzyFileSearchSessionUpdate": {
		"id":     {},
		"params": {},
	},
	"ClientRequestMCPServerEventStreamStart": {
		"id":     {},
		"params": {},
	},
	"ClientRequestMCPServerEventStreamStop": {
		"id":     {},
		"params": {},
	},
	"ClientRequestMemoryReset": {
		"id": {},
	},
	"ClientRequestMockExperimentalMethod": {
		"id":     {},
		"params": {},
	},
	"ClientRequestPluginSearch": {
		"id":     {},
		"params": {},
	},
	"ClientRequestProcessKill": {
		"id":     {},
		"params": {},
	},
	"ClientRequestProcessResizePTY": {
		"id":     {},
		"params": {},
	},
	"ClientRequestProcessSpawn": {
		"id":     {},
		"params": {},
	},
	"ClientRequestProcessWriteStdin": {
		"id":     {},
		"params": {},
	},
	"ClientRequestProjectCreate": {
		"id":     {},
		"params": {},
	},
	"ClientRequestProjectDelete": {
		"id":     {},
		"params": {},
	},
	"ClientRequestProjectImport": {
		"id":     {},
		"params": {},
	},
	"ClientRequestProjectList": {
		"id":     {},
		"params": {},
	},
	"ClientRequestProjectMove": {
		"id":     {},
		"params": {},
	},
	"ClientRequestProjectRead": {
		"id":     {},
		"params": {},
	},
	"ClientRequestProjectUpdate": {
		"id":     {},
		"params": {},
	},
	"ClientRequestRemoteControlClientList": {
		"id":     {},
		"params": {},
	},
	"ClientRequestRemoteControlClientRevoke": {
		"id":     {},
		"params": {},
	},
	"ClientRequestRemoteControlDisable": {
		"id":     {},
		"params": {},
	},
	"ClientRequestRemoteControlEnable": {
		"id":     {},
		"params": {},
	},
	"ClientRequestRemoteControlPairingStart": {
		"id":     {},
		"params": {},
	},
	"ClientRequestRemoteControlPairingStatus": {
		"id":     {},
		"params": {},
	},
	"ClientRequestRemoteControlStatusRead": {
		"id": {},
	},
	"ClientRequestServerDiagnostics": {
		"id":     {},
		"params": {},
	},
	"ClientRequestThreadBackgroundTerminalsClean": {
		"id":     {},
		"params": {},
	},
	"ClientRequestThreadBackgroundTerminalsList": {
		"id":     {},
		"params": {},
	},
	"ClientRequestThreadBackgroundTerminalsTerminate": {
		"id":     {},
		"params": {},
	},
	"ClientRequestThreadDecrementElicitation": {
		"id":     {},
		"params": {},
	},
	"ClientRequestThreadIncrementElicitation": {
		"id":     {},
		"params": {},
	},
	"ClientRequestThreadMemoryModeSet": {
		"id":     {},
		"params": {},
	},
	"ClientRequestThreadQueueAdd": {
		"id":     {},
		"params": {},
	},
	"ClientRequestThreadQueueDelete": {
		"id":     {},
		"params": {},
	},
	"ClientRequestThreadQueueList": {
		"id":     {},
		"params": {},
	},
	"ClientRequestThreadQueueReorder": {
		"id":     {},
		"params": {},
	},
	"ClientRequestThreadQueueStart": {
		"id":     {},
		"params": {},
	},
	"ClientRequestThreadQueueUpdate": {
		"id":     {},
		"params": {},
	},
	"ClientRequestThreadRealtimeAppendAudio": {
		"id":     {},
		"params": {},
	},
	"ClientRequestThreadRealtimeAppendSpeech": {
		"id":     {},
		"params": {},
	},
	"ClientRequestThreadRealtimeAppendText": {
		"id":     {},
		"params": {},
	},
	"ClientRequestThreadRealtimeListVoices": {
		"id":     {},
		"params": {},
	},
	"ClientRequestThreadRealtimeStart": {
		"id":     {},
		"params": {},
	},
	"ClientRequestThreadRealtimeStop": {
		"id":     {},
		"params": {},
	},
	"ClientRequestThreadSearch": {
		"id":     {},
		"params": {},
	},
	"ClientRequestThreadSearchOccurrences": {
		"id":     {},
		"params": {},
	},
	"ClientRequestThreadSettingsUpdate": {
		"id":     {},
		"params": {},
	},
	"ClientRequestThreadTimelineList": {
		"id":     {},
		"params": {},
	},
	"ClientRequestTurnSettingsUpdate": {
		"id":     {},
		"params": {},
	},
	"ClientRequestUserVerificationDelete": {
		"id":     {},
		"params": {},
	},
	"ClientRequestUserVerificationEnroll": {
		"id":     {},
		"params": {},
	},
	"ClientRequestUserVerificationStatus": {
		"id":     {},
		"params": {},
	},
	"ClientRequestUserVerificationVerify": {
		"id":     {},
		"params": {},
	},
	"CollaborationModeListResponse": {
		"data": {},
	},
	"CollaborationModeMask": {
		"mode":             {},
		"model":            {},
		"name":             {},
		"reasoning_effort": {},
	},
	"CommandExecParams": {
		"permissionProfile": {},
	},
	"CommandExecutionRequestApprovalParams": {
		"additionalPermissions": {},
		"availableDecisions":    {},
	},
	"Config": {
		"apps": {},
	},
	"ConfigRequirements": {
		"allowedApprovalsReviewers": {},
		"application":               {},
		"hooks":                     {},
		"network":                   {},
	},
	"CurrentTimeReadParams": {
		"threadId": {},
	},
	"CurrentTimeReadResponse": {
		"currentTimeAt": {},
	},
	"EnvironmentAddParams": {
		"connectTimeoutMs": {},
		"environmentId":    {},
		"execServerUrl":    {},
	},
	"EnvironmentInfoParams": {
		"environmentId": {},
	},
	"EnvironmentStatusParams": {
		"environmentId": {},
	},
	"EnvironmentStatusResponse": {
		"error":  {},
		"status": {},
	},
	"FuzzyFileSearchSessionStartParams": {
		"roots":     {},
		"sessionId": {},
	},
	"FuzzyFileSearchSessionStopParams": {
		"sessionId": {},
	},
	"FuzzyFileSearchSessionUpdateParams": {
		"query":     {},
		"sessionId": {},
	},
	"McpServerElicitationRequestParamsOpenaiUserVerification": {
		"challenge":   {},
		"description": {},
		"title":       {},
	},
	"McpServerEventStreamStartParams": {
		"_meta":          {},
		"arguments":      {},
		"name":           {},
		"server":         {},
		"subscriptionId": {},
		"threadId":       {},
	},
	"McpServerEventStreamStopParams": {
		"subscriptionId": {},
	},
	"MockExperimentalMethodParams": {
		"value": {},
	},
	"MockExperimentalMethodResponse": {
		"echoed": {},
	},
	"PluginSearchParams": {
		"cursor":     {},
		"cwds":       {},
		"limit":      {},
		"scope":      {},
		"searchTerm": {},
	},
	"PluginSearchResponse": {
		"data":       {},
		"nextCursor": {},
	},
	"PluginSearchResult": {
		"marketplaceName": {},
		"marketplacePath": {},
		"plugin":          {},
	},
	"ProcessKillParams": {
		"processHandle": {},
	},
	"ProcessResizePtyParams": {
		"processHandle": {},
		"size":          {},
	},
	"ProcessSpawnParams": {
		"command":            {},
		"cwd":                {},
		"env":                {},
		"outputBytesCap":     {},
		"processHandle":      {},
		"size":               {},
		"streamStdin":        {},
		"streamStdoutStderr": {},
		"timeoutMs":          {},
		"tty":                {},
	},
	"ProcessTerminalSize": {
		"cols": {},
		"rows": {},
	},
	"ProcessWriteStdinParams": {
		"closeStdin":    {},
		"deltaBase64":   {},
		"processHandle": {},
	},
	"Project": {
		"createdAt": {},
		"id":        {},
		"metadata":  {},
		"name":      {},
		"position":  {},
		"recencyAt": {},
		"roots":     {},
		"updatedAt": {},
	},
	"ProjectCreateParams": {
		"idempotencyKey": {},
		"metadata":       {},
		"name":           {},
		"roots":          {},
	},
	"ProjectCreateResponse": {
		"project": {},
	},
	"ProjectDeleteParams": {
		"projectId": {},
	},
	"ProjectImportParams": {
		"idempotencyKey": {},
		"metadata":       {},
		"name":           {},
		"roots":          {},
		"threads":        {},
	},
	"ProjectImportResponse": {
		"project": {},
	},
	"ProjectListParams": {
		"cursor":        {},
		"limit":         {},
		"sortDirection": {},
		"sortKey":       {},
	},
	"ProjectListResponse": {
		"data":       {},
		"nextCursor": {},
	},
	"ProjectMoveParams": {
		"beforeProjectId": {},
		"projectId":       {},
	},
	"ProjectReadParams": {
		"projectId": {},
	},
	"ProjectReadResponse": {
		"project": {},
	},
	"ProjectRoot": {
		"path": {},
	},
	"ProjectUpdateParams": {
		"metadata":  {},
		"name":      {},
		"projectId": {},
		"roots":     {},
	},
	"ProjectUpdateResponse": {
		"project": {},
	},
	"QueuedSubmission": {
		"clientUserMessageId": {},
		"id":                  {},
		"input":               {},
	},
	"RealtimeVoicesList": {
		"defaultV1": {},
		"defaultV2": {},
		"v1":        {},
		"v2":        {},
	},
	"RemoteControlClientsListParams": {
		"cursor":        {},
		"environmentId": {},
		"limit":         {},
		"order":         {},
	},
	"RemoteControlClientsRevokeParams": {
		"clientId":      {},
		"environmentId": {},
	},
	"RemoteControlDisableResponse": {
		"environmentId":  {},
		"installationId": {},
		"serverName":     {},
		"status":         {},
	},
	"RemoteControlEnableResponse": {
		"environmentId":  {},
		"installationId": {},
		"serverName":     {},
		"status":         {},
	},
	"RemoteControlPairingStartParams": {
		"manualCode": {},
	},
	"RemoteControlPairingStartResponse": {
		"environmentId":     {},
		"expiresAt":         {},
		"manualPairingCode": {},
		"pairingCode":       {},
	},
	"RemoteControlPairingStatusParams": {
		"manualPairingCode": {},
		"pairingCode":       {},
	},
	"RemoteControlPairingStatusResponse": {
		"claimed": {},
	},
	"RemoteControlStatusReadResponse": {
		"environmentId":  {},
		"installationId": {},
		"serverName":     {},
		"status":         {},
	},
	"ServerDiagnosticsGauge": {
		"name":  {},
		"value": {},
	},
	"ServerDiagnosticsProcess": {
		"id":                     {},
		"physicalFootprintBytes": {},
		"residentMemoryBytes":    {},
	},
	"ServerDiagnosticsResponse": {
		"gauges":  {},
		"process": {},
	},
	"ServerRequestCurrentTimeRead": {
		"id":     {},
		"params": {},
	},
	"Thread": {
		"canAcceptDirectInput": {},
		"daybreakEnabled":      {},
		"environments":         {},
		"extra":                {},
	},
	"ThreadBackgroundTerminalsCleanParams": {
		"threadId": {},
	},
	"ThreadBackgroundTerminalsListParams": {
		"cursor":   {},
		"limit":    {},
		"threadId": {},
	},
	"ThreadBackgroundTerminalsTerminateParams": {
		"processId": {},
		"threadId":  {},
	},
	"ThreadBackgroundTerminalsTerminateResponse": {
		"terminated": {},
	},
	"ThreadDecrementElicitationParams": {
		"threadId": {},
	},
	"ThreadDecrementElicitationResponse": {
		"count":  {},
		"paused": {},
	},
	"ThreadForkParams": {
		"beforeTurnId":          {},
		"deferGoalContinuation": {},
		"path":                  {},
		"permissions":           {},
		"runtimeWorkspaceRoots": {},
	},
	"ThreadForkResponse": {
		"activePermissionProfile": {},
		"multiAgentMode":          {},
		"runtimeWorkspaceRoots":   {},
	},
	"ThreadIncrementElicitationParams": {
		"threadId": {},
	},
	"ThreadIncrementElicitationResponse": {
		"count":  {},
		"paused": {},
	},
	"ThreadListParams": {
		"ancestorThreadId": {},
		"parentThreadId":   {},
		"projectId":        {},
	},
	"ThreadMemoryModeSetParams": {
		"mode":     {},
		"threadId": {},
	},
	"ThreadMetadataUpdateParams": {
		"daybreakEnabled": {},
		"projectId":       {},
	},
	"ThreadQueueAddParams": {
		"clientUserMessageId": {},
		"input":               {},
		"threadId":            {},
	},
	"ThreadQueueAddResponse": {
		"queuedSubmission": {},
	},
	"ThreadQueueDeleteParams": {
		"queuedSubmissionId": {},
		"threadId":           {},
	},
	"ThreadQueueDeleteResponse": {
		"deleted": {},
	},
	"ThreadQueueListParams": {
		"cursor":   {},
		"limit":    {},
		"threadId": {},
	},
	"ThreadQueueListResponse": {
		"data":       {},
		"nextCursor": {},
	},
	"ThreadQueueReorderParams": {
		"queuedSubmissionIds": {},
		"threadId":            {},
	},
	"ThreadQueueStartParams": {
		"queuedSubmissionId": {},
		"threadId":           {},
	},
	"ThreadQueueStartResponse": {
		"turn": {},
	},
	"ThreadQueueUpdateParams": {
		"input":              {},
		"queuedSubmissionId": {},
		"threadId":           {},
	},
	"ThreadQueueUpdateResponse": {
		"queuedSubmission": {},
	},
	"ThreadRealtimeAppendAudioParams": {
		"audio":    {},
		"threadId": {},
	},
	"ThreadRealtimeAppendSpeechParams": {
		"text":     {},
		"threadId": {},
	},
	"ThreadRealtimeAppendTextParams": {
		"role":     {},
		"text":     {},
		"threadId": {},
	},
	"ThreadRealtimeInitialItem": {
		"role": {},
		"text": {},
	},
	"ThreadRealtimeListVoicesResponse": {
		"voices": {},
	},
	"ThreadRealtimeStartParams": {
		"clientManagedHandoffs":               {},
		"codexResponseHandoffChannelPrefixes": {},
		"codexResponseHandoffMode":            {},
		"codexResponseItemPrefix":             {},
		"codexResponsesAsItems":               {},
		"delegationAckFiller":                 {},
		"flushTranscriptTailOnSessionEnd":     {},
		"includeStartupContext":               {},
		"initialItems":                        {},
		"model":                               {},
		"outputModality":                      {},
		"prompt":                              {},
		"realtimeEndInstructions":             {},
		"realtimeSessionId":                   {},
		"realtimeStartInstructions":           {},
		"threadId":                            {},
		"transport":                           {},
		"version":                             {},
		"voice":                               {},
	},
	"ThreadRealtimeStartTransportExistingCall": {
		"callId": {},
	},
	"ThreadRealtimeStartTransportWebrtc": {
		"sdp": {},
	},
	"ThreadRealtimeStopParams": {
		"threadId": {},
	},
	"ThreadResumeParams": {
		"history":               {},
		"initialTurnsPage":      {},
		"path":                  {},
		"permissions":           {},
		"runtimeWorkspaceRoots": {},
	},
	"ThreadResumeResponse": {
		"activePermissionProfile": {},
		"initialTurnsPage":        {},
		"multiAgentMode":          {},
		"runtimeWorkspaceRoots":   {},
	},
	"ThreadSearchOccurrence": {
		"itemId":            {},
		"snippet":           {},
		"snippetMatchRange": {},
		"turnCursor":        {},
		"turnId":            {},
	},
	"ThreadSearchOccurrencesParams": {
		"cursor":     {},
		"limit":      {},
		"searchTerm": {},
		"threadId":   {},
	},
	"ThreadSearchOccurrencesResponse": {
		"data":       {},
		"nextCursor": {},
	},
	"ThreadSearchParams": {
		"archived":      {},
		"cursor":        {},
		"limit":         {},
		"searchTerm":    {},
		"sortDirection": {},
		"sortKey":       {},
		"sourceKinds":   {},
	},
	"ThreadSearchTextRange": {
		"end":   {},
		"start": {},
	},
	"ThreadSettings": {
		"multiAgentMode": {},
	},
	"ThreadSettingsUpdateParams": {
		"approvalPolicy":    {},
		"approvalsReviewer": {},
		"collaborationMode": {},
		"cwd":               {},
		"effort":            {},
		"model":             {},
		"multiAgentMode":    {},
		"permissions":       {},
		"personality":       {},
		"sandboxPolicy":     {},
		"serviceTier":       {},
		"summary":           {},
		"threadId":          {},
	},
	"ThreadStartParams": {
		"allowProviderModelFallback": {},
		"dynamicTools":               {},
		"environments":               {},
		"experimentalRawEvents":      {},
		"historyMode":                {},
		"mockExperimentalField":      {},
		"multiAgentMode":             {},
		"permissions":                {},
		"projectId":                  {},
		"runtimeWorkspaceRoots":      {},
		"selectedCapabilityRoots":    {},
	},
	"ThreadStartResponse": {
		"activePermissionProfile": {},
		"multiAgentMode":          {},
		"runtimeWorkspaceRoots":   {},
	},
	"ThreadTimelineListParams": {
		"cursor":   {},
		"limit":    {},
		"threadId": {},
	},
	"TurnSettingsUpdateParams": {
		"approvalsReviewer": {},
		"effort":            {},
		"model":             {},
		"serviceTier":       {},
		"summary":           {},
		"threadId":          {},
		"turnId":            {},
	},
	"TurnSettingsUpdateResponse": {
		"status": {},
	},
	"TurnStartParams": {
		"additionalContext":          {},
		"collaborationMode":          {},
		"cyberAccessProgram":         {},
		"environments":               {},
		"multiAgentMode":             {},
		"permissions":                {},
		"responsesapiClientMetadata": {},
		"runtimeWorkspaceRoots":      {},
	},
	"TurnSteerParams": {
		"additionalContext":          {},
		"responsesapiClientMetadata": {},
	},
	"UserVerificationEnrollResponse": {
		"credentialId": {},
	},
	"UserVerificationErrorDetailsCancelled": {
		"reason": {},
	},
	"UserVerificationErrorDetailsFailed": {
		"reason": {},
	},
	"UserVerificationErrorDetailsInvalidRequest": {
		"reason": {},
	},
	"UserVerificationErrorDetailsUnavailable": {
		"reason": {},
	},
	"UserVerificationProof": {
		"credentialId": {},
		"signature":    {},
	},
	"UserVerificationRpcError": {
		"code":    {},
		"data":    {},
		"message": {},
	},
	"UserVerificationStatusResponse": {
		"credentialId":       {},
		"unavailableMessage": {},
		"unavailableReason":  {},
	},
	"UserVerificationVerifyParams": {
		"challenge":   {},
		"description": {},
		"title":       {},
	},
	"UserVerificationVerifyResponse": {
		"proof": {},
	},
}

var ExperimentalUnionValues = map[string]map[string]struct{}{
	"AwsCredentialType": {
		"accessKeys":    {},
		"bedrockApiKey": {},
	},
	"BedrockSetupParams": {
		"environment": {},
		"profile":     {},
	},
	"ClientRequest": {
		"account/bedrock/discover":             {},
		"account/bedrock/setup":                {},
		"collaborationMode/list":               {},
		"environment/add":                      {},
		"environment/info":                     {},
		"environment/status":                   {},
		"fuzzyFileSearch/sessionStart":         {},
		"fuzzyFileSearch/sessionStop":          {},
		"fuzzyFileSearch/sessionUpdate":        {},
		"mcpServer/event/stream/start":         {},
		"mcpServer/event/stream/stop":          {},
		"memory/reset":                         {},
		"mock/experimentalMethod":              {},
		"plugin/search":                        {},
		"process/kill":                         {},
		"process/resizePty":                    {},
		"process/spawn":                        {},
		"process/writeStdin":                   {},
		"project/create":                       {},
		"project/delete":                       {},
		"project/import":                       {},
		"project/list":                         {},
		"project/move":                         {},
		"project/read":                         {},
		"project/update":                       {},
		"remoteControl/client/list":            {},
		"remoteControl/client/revoke":          {},
		"remoteControl/disable":                {},
		"remoteControl/enable":                 {},
		"remoteControl/pairing/start":          {},
		"remoteControl/pairing/status":         {},
		"remoteControl/status/read":            {},
		"server/diagnostics":                   {},
		"thread/backgroundTerminals/clean":     {},
		"thread/backgroundTerminals/list":      {},
		"thread/backgroundTerminals/terminate": {},
		"thread/decrement_elicitation":         {},
		"thread/increment_elicitation":         {},
		"thread/memoryMode/set":                {},
		"thread/queue/add":                     {},
		"thread/queue/delete":                  {},
		"thread/queue/list":                    {},
		"thread/queue/reorder":                 {},
		"thread/queue/start":                   {},
		"thread/queue/update":                  {},
		"thread/realtime/appendAudio":          {},
		"thread/realtime/appendSpeech":         {},
		"thread/realtime/appendText":           {},
		"thread/realtime/listVoices":           {},
		"thread/realtime/start":                {},
		"thread/realtime/stop":                 {},
		"thread/search":                        {},
		"thread/searchOccurrences":             {},
		"thread/settings/update":               {},
		"thread/timeline/list":                 {},
		"turn/settings/update":                 {},
		"userVerification/delete":              {},
		"userVerification/enroll":              {},
		"userVerification/status":              {},
		"userVerification/verify":              {},
	},
	"EnvironmentStatus": {
		"disconnected": {},
		"pending":      {},
		"ready":        {},
		"unknown":      {},
	},
	"McpServerElicitationRequestParams": {
		"openai/userVerification": {},
	},
	"RemoteControlClientsListOrder": {
		"asc":  {},
		"desc": {},
	},
	"ServerRequest": {
		"currentTime/read": {},
	},
	"ThreadRealtimeStartTransport": {
		"existingCall": {},
		"webrtc":       {},
		"websocket":    {},
	},
	"TurnSettingsUpdateStatus": {
		"applied":           {},
		"targetUnavailable": {},
	},
	"UserVerificationCancellationReason": {
		"interrupted":   {},
		"userCancelled": {},
	},
	"UserVerificationErrorDetails": {
		"cancelled":      {},
		"failed":         {},
		"invalidRequest": {},
		"unavailable":    {},
	},
	"UserVerificationFailureReason": {
		"authenticationFailed": {},
		"providerError":        {},
		"serviceError":         {},
		"timeout":              {},
	},
	"UserVerificationInvalidRequestReason": {
		"invalidParams": {},
	},
	"UserVerificationUnavailableReason": {
		"biometricsUnavailable": {},
		"credentialMissing":     {},
		"providerUnavailable":   {},
	},
}

var ExperimentalChildTypes = map[string]map[string]string{
	"AccountChatGPT": {
		"planType": "PlanType",
	},
	"AccountLoginCompletedNotification": {
		"onboardingEntrypoint": "DesktopOnboardingEntrypoint",
	},
	"AccountRateLimitsUpdatedNotification": {
		"rateLimits": "RateLimitSnapshot",
	},
	"AccountUpdatedNotification": {
		"authMode": "AuthMode",
		"planType": "PlanType",
	},
	"AdditionalContextEntry": {
		"kind": "AdditionalContextKind",
	},
	"AdditionalFileSystemPermissions": {
		"entries": "FileSystemSandboxEntry",
	},
	"AdditionalPermissionProfile": {
		"fileSystem": "AdditionalFileSystemPermissions",
		"network":    "AdditionalNetworkPermissions",
	},
	"AppConfig": {
		"approvals_reviewer":          "ApprovalsReviewer",
		"default_tools_approval_mode": "AppToolApproval",
		"links":                       "AppLinksConfig",
		"tools":                       "AppToolsConfig",
	},
	"AppInfo": {
		"appMetadata": "AppMetadata",
		"branding":    "AppBranding",
	},
	"AppListUpdatedNotification": {
		"data": "AppInfo",
	},
	"AppMetadata": {
		"review":      "AppReview",
		"screenshots": "AppScreenshot",
	},
	"AppTemplateSummary": {
		"reason": "AppTemplateUnavailableReason",
	},
	"AppToolConfig": {
		"approval_mode": "AppToolApproval",
	},
	"ApplicationNetworkRequirements": {
		"domains": "NetworkDomainPermission",
	},
	"ApplicationRequirements": {
		"network": "ApplicationNetworkRequirements",
	},
	"ApplyPatchApprovalParams": {
		"fileChanges": "FileChange",
	},
	"ApplyPatchApprovalResponse": {
		"decision": "ReviewDecision",
	},
	"AppsConfig": {
		"_default": "AppsDefaultConfig",
	},
	"AppsDefaultConfig": {
		"approvals_reviewer":          "ApprovalsReviewer",
		"default_tools_approval_mode": "AppToolApproval",
	},
	"AppsInstalledResponse": {
		"apps": "InstalledApp",
	},
	"AppsListResponse": {
		"data": "AppInfo",
	},
	"AppsReadResponse": {
		"apps": "ConnectorMetadata",
	},
	"BedrockDiscoverResponse": {
		"environmentCredentials": "BedrockEnvironmentCredential",
		"profiles":               "BedrockAwsProfile",
	},
	"BedrockEnvironmentCredential": {
		"type": "AwsCredentialType",
	},
	"BrowserUseConfig": {
		"default_origin_policy": "BrowserUseOriginPolicyConfig",
		"origins":               "BrowserUseOriginPolicyConfig",
	},
	"BrowserUseOriginPolicy": {
		"access":                 "AllowDenyRequirement",
		"accessApprovalLifetime": "BrowserUseAccessApprovalLifetime",
		"autoReview":             "AllowDenyRequirement",
		"downloads":              "AllowDenyRequirement",
		"fullCdpAccess":          "AllowDenyRequirement",
		"uploads":                "AllowDenyRequirement",
	},
	"BrowserUseOriginPolicyConfig": {
		"access":          "AllowDenyRequirement",
		"downloads":       "AllowDenyRequirement",
		"full_cdp_access": "AllowDenyRequirement",
		"uploads":         "AllowDenyRequirement",
	},
	"BrowserUseRequirements": {
		"defaultOriginPolicy": "BrowserUseOriginPolicy",
		"origins":             "BrowserUseOriginPolicy",
	},
	"CancelLoginAccountResponse": {
		"status": "CancelLoginAccountStatus",
	},
	"ChatgptAuthTokensRefreshParams": {
		"reason": "ChatgptAuthTokensRefreshReason",
	},
	"ClientRequestAccountBedrockDiscover": {
		"id":     "RequestId",
		"params": "BedrockDiscoverParams",
	},
	"ClientRequestAccountBedrockSetup": {
		"id":     "RequestId",
		"params": "BedrockSetupParams",
	},
	"ClientRequestAccountLoginCancel": {
		"id":     "RequestId",
		"params": "CancelLoginAccountParams",
	},
	"ClientRequestAccountLoginStart": {
		"id":     "RequestId",
		"params": "LoginAccountParams",
	},
	"ClientRequestAccountLogout": {
		"id": "RequestId",
	},
	"ClientRequestAccountRateLimitResetCreditConsume": {
		"id":     "RequestId",
		"params": "ConsumeAccountRateLimitResetCreditParams",
	},
	"ClientRequestAccountRateLimitsRead": {
		"id":     "RequestId",
		"params": "GetAccountRateLimitsParams",
	},
	"ClientRequestAccountRead": {
		"id":     "RequestId",
		"params": "GetAccountParams",
	},
	"ClientRequestAccountSendAddCreditsNudgeEmail": {
		"id":     "RequestId",
		"params": "SendAddCreditsNudgeEmailParams",
	},
	"ClientRequestAccountUsageRead": {
		"id":     "RequestId",
		"params": "GetAccountTokenUsageParams",
	},
	"ClientRequestAccountWorkspaceMessagesRead": {
		"id": "RequestId",
	},
	"ClientRequestAppInstalled": {
		"id":     "RequestId",
		"params": "AppsInstalledParams",
	},
	"ClientRequestAppList": {
		"id":     "RequestId",
		"params": "AppsListParams",
	},
	"ClientRequestAppRead": {
		"id":     "RequestId",
		"params": "AppsReadParams",
	},
	"ClientRequestCollaborationModeList": {
		"id":     "RequestId",
		"params": "CollaborationModeListParams",
	},
	"ClientRequestCommandExec": {
		"id":     "RequestId",
		"params": "CommandExecParams",
	},
	"ClientRequestCommandExecResize": {
		"id":     "RequestId",
		"params": "CommandExecResizeParams",
	},
	"ClientRequestCommandExecTerminate": {
		"id":     "RequestId",
		"params": "CommandExecTerminateParams",
	},
	"ClientRequestCommandExecWrite": {
		"id":     "RequestId",
		"params": "CommandExecWriteParams",
	},
	"ClientRequestConfigBatchWrite": {
		"id":     "RequestId",
		"params": "ConfigBatchWriteParams",
	},
	"ClientRequestConfigMCPServerReload": {
		"id": "RequestId",
	},
	"ClientRequestConfigRead": {
		"id":     "RequestId",
		"params": "ConfigReadParams",
	},
	"ClientRequestConfigRequirementsRead": {
		"id": "RequestId",
	},
	"ClientRequestConfigValueWrite": {
		"id":     "RequestId",
		"params": "ConfigValueWriteParams",
	},
	"ClientRequestEnvironmentAdd": {
		"id":     "RequestId",
		"params": "EnvironmentAddParams",
	},
	"ClientRequestEnvironmentInfo": {
		"id":     "RequestId",
		"params": "EnvironmentInfoParams",
	},
	"ClientRequestEnvironmentStatus": {
		"id":     "RequestId",
		"params": "EnvironmentStatusParams",
	},
	"ClientRequestExperimentalFeatureEnablementSet": {
		"id":     "RequestId",
		"params": "ExperimentalFeatureEnablementSetParams",
	},
	"ClientRequestExperimentalFeatureList": {
		"id":     "RequestId",
		"params": "ExperimentalFeatureListParams",
	},
	"ClientRequestExternalAgentConfigDetect": {
		"id":     "RequestId",
		"params": "ExternalAgentConfigDetectParams",
	},
	"ClientRequestExternalAgentConfigImport": {
		"id":     "RequestId",
		"params": "ExternalAgentConfigImportParams",
	},
	"ClientRequestExternalAgentConfigImportReadHistories": {
		"id": "RequestId",
	},
	"ClientRequestExternalAgentConfigImportRecordHistory": {
		"id":     "RequestId",
		"params": "ExternalAgentConfigImportHistoryRecordParams",
	},
	"ClientRequestFSCopy": {
		"id":     "RequestId",
		"params": "FsCopyParams",
	},
	"ClientRequestFSCreateDirectory": {
		"id":     "RequestId",
		"params": "FsCreateDirectoryParams",
	},
	"ClientRequestFSGetMetadata": {
		"id":     "RequestId",
		"params": "FsGetMetadataParams",
	},
	"ClientRequestFSReadDirectory": {
		"id":     "RequestId",
		"params": "FsReadDirectoryParams",
	},
	"ClientRequestFSReadFile": {
		"id":     "RequestId",
		"params": "FsReadFileParams",
	},
	"ClientRequestFSRemove": {
		"id":     "RequestId",
		"params": "FsRemoveParams",
	},
	"ClientRequestFSUnwatch": {
		"id":     "RequestId",
		"params": "FsUnwatchParams",
	},
	"ClientRequestFSWatch": {
		"id":     "RequestId",
		"params": "FsWatchParams",
	},
	"ClientRequestFSWriteFile": {
		"id":     "RequestId",
		"params": "FsWriteFileParams",
	},
	"ClientRequestFeedbackUpload": {
		"id":     "RequestId",
		"params": "FeedbackUploadParams",
	},
	"ClientRequestFuzzyFileSearch": {
		"id":     "RequestId",
		"params": "FuzzyFileSearchParams",
	},
	"ClientRequestFuzzyFileSearchSessionStart": {
		"id":     "RequestId",
		"params": "FuzzyFileSearchSessionStartParams",
	},
	"ClientRequestFuzzyFileSearchSessionStop": {
		"id":     "RequestId",
		"params": "FuzzyFileSearchSessionStopParams",
	},
	"ClientRequestFuzzyFileSearchSessionUpdate": {
		"id":     "RequestId",
		"params": "FuzzyFileSearchSessionUpdateParams",
	},
	"ClientRequestHooksList": {
		"id":     "RequestId",
		"params": "HooksListParams",
	},
	"ClientRequestInitialize": {
		"id":     "RequestId",
		"params": "InitializeParams",
	},
	"ClientRequestMCPServerEventStreamStart": {
		"id":     "RequestId",
		"params": "McpServerEventStreamStartParams",
	},
	"ClientRequestMCPServerEventStreamStop": {
		"id":     "RequestId",
		"params": "McpServerEventStreamStopParams",
	},
	"ClientRequestMCPServerOAuthLogin": {
		"id":     "RequestId",
		"params": "McpServerOauthLoginParams",
	},
	"ClientRequestMCPServerResourceRead": {
		"id":     "RequestId",
		"params": "McpResourceReadParams",
	},
	"ClientRequestMCPServerStatusList": {
		"id":     "RequestId",
		"params": "ListMcpServerStatusParams",
	},
	"ClientRequestMCPServerToolCall": {
		"id":     "RequestId",
		"params": "McpServerToolCallParams",
	},
	"ClientRequestMarketplaceAdd": {
		"id":     "RequestId",
		"params": "MarketplaceAddParams",
	},
	"ClientRequestMarketplaceRemove": {
		"id":     "RequestId",
		"params": "MarketplaceRemoveParams",
	},
	"ClientRequestMarketplaceUpgrade": {
		"id":     "RequestId",
		"params": "MarketplaceUpgradeParams",
	},
	"ClientRequestMemoryReset": {
		"id": "RequestId",
	},
	"ClientRequestMockExperimentalMethod": {
		"id":     "RequestId",
		"params": "MockExperimentalMethodParams",
	},
	"ClientRequestModelList": {
		"id":     "RequestId",
		"params": "ModelListParams",
	},
	"ClientRequestModelProviderCapabilitiesRead": {
		"id":     "RequestId",
		"params": "ModelProviderCapabilitiesReadParams",
	},
	"ClientRequestPermissionProfileList": {
		"id":     "RequestId",
		"params": "PermissionProfileListParams",
	},
	"ClientRequestPluginInstall": {
		"id":     "RequestId",
		"params": "PluginInstallParams",
	},
	"ClientRequestPluginInstalled": {
		"id":     "RequestId",
		"params": "PluginInstalledParams",
	},
	"ClientRequestPluginList": {
		"id":     "RequestId",
		"params": "PluginListParams",
	},
	"ClientRequestPluginRead": {
		"id":     "RequestId",
		"params": "PluginReadParams",
	},
	"ClientRequestPluginReconcile": {
		"id":     "RequestId",
		"params": "PluginReconcileParams",
	},
	"ClientRequestPluginSearch": {
		"id":     "RequestId",
		"params": "PluginSearchParams",
	},
	"ClientRequestPluginShareCheckout": {
		"id":     "RequestId",
		"params": "PluginShareCheckoutParams",
	},
	"ClientRequestPluginShareDelete": {
		"id":     "RequestId",
		"params": "PluginShareDeleteParams",
	},
	"ClientRequestPluginShareList": {
		"id":     "RequestId",
		"params": "PluginShareListParams",
	},
	"ClientRequestPluginShareSave": {
		"id":     "RequestId",
		"params": "PluginShareSaveParams",
	},
	"ClientRequestPluginShareUpdateTargets": {
		"id":     "RequestId",
		"params": "PluginShareUpdateTargetsParams",
	},
	"ClientRequestPluginSkillRead": {
		"id":     "RequestId",
		"params": "PluginSkillReadParams",
	},
	"ClientRequestPluginUninstall": {
		"id":     "RequestId",
		"params": "PluginUninstallParams",
	},
	"ClientRequestProcessKill": {
		"id":     "RequestId",
		"params": "ProcessKillParams",
	},
	"ClientRequestProcessResizePTY": {
		"id":     "RequestId",
		"params": "ProcessResizePtyParams",
	},
	"ClientRequestProcessSpawn": {
		"id":     "RequestId",
		"params": "ProcessSpawnParams",
	},
	"ClientRequestProcessWriteStdin": {
		"id":     "RequestId",
		"params": "ProcessWriteStdinParams",
	},
	"ClientRequestProjectCreate": {
		"id":     "RequestId",
		"params": "ProjectCreateParams",
	},
	"ClientRequestProjectDelete": {
		"id":     "RequestId",
		"params": "ProjectDeleteParams",
	},
	"ClientRequestProjectImport": {
		"id":     "RequestId",
		"params": "ProjectImportParams",
	},
	"ClientRequestProjectList": {
		"id":     "RequestId",
		"params": "ProjectListParams",
	},
	"ClientRequestProjectMove": {
		"id":     "RequestId",
		"params": "ProjectMoveParams",
	},
	"ClientRequestProjectRead": {
		"id":     "RequestId",
		"params": "ProjectReadParams",
	},
	"ClientRequestProjectUpdate": {
		"id":     "RequestId",
		"params": "ProjectUpdateParams",
	},
	"ClientRequestRemoteControlClientList": {
		"id":     "RequestId",
		"params": "RemoteControlClientsListParams",
	},
	"ClientRequestRemoteControlClientRevoke": {
		"id":     "RequestId",
		"params": "RemoteControlClientsRevokeParams",
	},
	"ClientRequestRemoteControlDisable": {
		"id":     "RequestId",
		"params": "RemoteControlDisableParams",
	},
	"ClientRequestRemoteControlEnable": {
		"id":     "RequestId",
		"params": "RemoteControlEnableParams",
	},
	"ClientRequestRemoteControlPairingStart": {
		"id":     "RequestId",
		"params": "RemoteControlPairingStartParams",
	},
	"ClientRequestRemoteControlPairingStatus": {
		"id":     "RequestId",
		"params": "RemoteControlPairingStatusParams",
	},
	"ClientRequestRemoteControlStatusRead": {
		"id": "RequestId",
	},
	"ClientRequestReviewStart": {
		"id":     "RequestId",
		"params": "ReviewStartParams",
	},
	"ClientRequestServerDiagnostics": {
		"id":     "RequestId",
		"params": "ServerDiagnosticsParams",
	},
	"ClientRequestSkillsConfigWrite": {
		"id":     "RequestId",
		"params": "SkillsConfigWriteParams",
	},
	"ClientRequestSkillsExtraRootsSet": {
		"id":     "RequestId",
		"params": "SkillsExtraRootsSetParams",
	},
	"ClientRequestSkillsList": {
		"id":     "RequestId",
		"params": "SkillsListParams",
	},
	"ClientRequestThreadApproveGuardianDeniedAction": {
		"id":     "RequestId",
		"params": "ThreadApproveGuardianDeniedActionParams",
	},
	"ClientRequestThreadArchive": {
		"id":     "RequestId",
		"params": "ThreadArchiveParams",
	},
	"ClientRequestThreadBackgroundTerminalsClean": {
		"id":     "RequestId",
		"params": "ThreadBackgroundTerminalsCleanParams",
	},
	"ClientRequestThreadBackgroundTerminalsList": {
		"id":     "RequestId",
		"params": "ThreadBackgroundTerminalsListParams",
	},
	"ClientRequestThreadBackgroundTerminalsTerminate": {
		"id":     "RequestId",
		"params": "ThreadBackgroundTerminalsTerminateParams",
	},
	"ClientRequestThreadCompactStart": {
		"id":     "RequestId",
		"params": "ThreadCompactStartParams",
	},
	"ClientRequestThreadDecrementElicitation": {
		"id":     "RequestId",
		"params": "ThreadDecrementElicitationParams",
	},
	"ClientRequestThreadDelete": {
		"id":     "RequestId",
		"params": "ThreadDeleteParams",
	},
	"ClientRequestThreadFork": {
		"id":     "RequestId",
		"params": "ThreadForkParams",
	},
	"ClientRequestThreadGoalClear": {
		"id":     "RequestId",
		"params": "ThreadGoalClearParams",
	},
	"ClientRequestThreadGoalGet": {
		"id":     "RequestId",
		"params": "ThreadGoalGetParams",
	},
	"ClientRequestThreadGoalSet": {
		"id":     "RequestId",
		"params": "ThreadGoalSetParams",
	},
	"ClientRequestThreadIncrementElicitation": {
		"id":     "RequestId",
		"params": "ThreadIncrementElicitationParams",
	},
	"ClientRequestThreadInjectItems": {
		"id":     "RequestId",
		"params": "ThreadInjectItemsParams",
	},
	"ClientRequestThreadItemsList": {
		"id":     "RequestId",
		"params": "ThreadItemsListParams",
	},
	"ClientRequestThreadList": {
		"id":     "RequestId",
		"params": "ThreadListParams",
	},
	"ClientRequestThreadLoadedList": {
		"id":     "RequestId",
		"params": "ThreadLoadedListParams",
	},
	"ClientRequestThreadMemoryModeSet": {
		"id":     "RequestId",
		"params": "ThreadMemoryModeSetParams",
	},
	"ClientRequestThreadMetadataUpdate": {
		"id":     "RequestId",
		"params": "ThreadMetadataUpdateParams",
	},
	"ClientRequestThreadNameSet": {
		"id":     "RequestId",
		"params": "ThreadSetNameParams",
	},
	"ClientRequestThreadQueueAdd": {
		"id":     "RequestId",
		"params": "ThreadQueueAddParams",
	},
	"ClientRequestThreadQueueDelete": {
		"id":     "RequestId",
		"params": "ThreadQueueDeleteParams",
	},
	"ClientRequestThreadQueueList": {
		"id":     "RequestId",
		"params": "ThreadQueueListParams",
	},
	"ClientRequestThreadQueueReorder": {
		"id":     "RequestId",
		"params": "ThreadQueueReorderParams",
	},
	"ClientRequestThreadQueueStart": {
		"id":     "RequestId",
		"params": "ThreadQueueStartParams",
	},
	"ClientRequestThreadQueueUpdate": {
		"id":     "RequestId",
		"params": "ThreadQueueUpdateParams",
	},
	"ClientRequestThreadRead": {
		"id":     "RequestId",
		"params": "ThreadReadParams",
	},
	"ClientRequestThreadRealtimeAppendAudio": {
		"id":     "RequestId",
		"params": "ThreadRealtimeAppendAudioParams",
	},
	"ClientRequestThreadRealtimeAppendSpeech": {
		"id":     "RequestId",
		"params": "ThreadRealtimeAppendSpeechParams",
	},
	"ClientRequestThreadRealtimeAppendText": {
		"id":     "RequestId",
		"params": "ThreadRealtimeAppendTextParams",
	},
	"ClientRequestThreadRealtimeListVoices": {
		"id":     "RequestId",
		"params": "ThreadRealtimeListVoicesParams",
	},
	"ClientRequestThreadRealtimeStart": {
		"id":     "RequestId",
		"params": "ThreadRealtimeStartParams",
	},
	"ClientRequestThreadRealtimeStop": {
		"id":     "RequestId",
		"params": "ThreadRealtimeStopParams",
	},
	"ClientRequestThreadResume": {
		"id":     "RequestId",
		"params": "ThreadResumeParams",
	},
	"ClientRequestThreadRevert": {
		"id":     "RequestId",
		"params": "ThreadRevertParams",
	},
	"ClientRequestThreadRollback": {
		"id":     "RequestId",
		"params": "ThreadRollbackParams",
	},
	"ClientRequestThreadSearch": {
		"id":     "RequestId",
		"params": "ThreadSearchParams",
	},
	"ClientRequestThreadSearchOccurrences": {
		"id":     "RequestId",
		"params": "ThreadSearchOccurrencesParams",
	},
	"ClientRequestThreadSectionCreate": {
		"id":     "RequestId",
		"params": "ThreadSectionCreateParams",
	},
	"ClientRequestThreadSectionDelete": {
		"id":     "RequestId",
		"params": "ThreadSectionDeleteParams",
	},
	"ClientRequestThreadSectionList": {
		"id":     "RequestId",
		"params": "ThreadSectionListParams",
	},
	"ClientRequestThreadSectionMove": {
		"id":     "RequestId",
		"params": "ThreadSectionMoveParams",
	},
	"ClientRequestThreadSectionUpdate": {
		"id":     "RequestId",
		"params": "ThreadSectionUpdateParams",
	},
	"ClientRequestThreadSettingsUpdate": {
		"id":     "RequestId",
		"params": "ThreadSettingsUpdateParams",
	},
	"ClientRequestThreadShellCommand": {
		"id":     "RequestId",
		"params": "ThreadShellCommandParams",
	},
	"ClientRequestThreadStart": {
		"id":     "RequestId",
		"params": "ThreadStartParams",
	},
	"ClientRequestThreadTimelineList": {
		"id":     "RequestId",
		"params": "ThreadTimelineListParams",
	},
	"ClientRequestThreadTurnsList": {
		"id":     "RequestId",
		"params": "ThreadTurnsListParams",
	},
	"ClientRequestThreadUnarchive": {
		"id":     "RequestId",
		"params": "ThreadUnarchiveParams",
	},
	"ClientRequestThreadUnsubscribe": {
		"id":     "RequestId",
		"params": "ThreadUnsubscribeParams",
	},
	"ClientRequestTurnInterrupt": {
		"id":     "RequestId",
		"params": "TurnInterruptParams",
	},
	"ClientRequestTurnSettingsUpdate": {
		"id":     "RequestId",
		"params": "TurnSettingsUpdateParams",
	},
	"ClientRequestTurnStart": {
		"id":     "RequestId",
		"params": "TurnStartParams",
	},
	"ClientRequestTurnSteer": {
		"id":     "RequestId",
		"params": "TurnSteerParams",
	},
	"ClientRequestUserVerificationDelete": {
		"id":     "RequestId",
		"params": "UserVerificationDeleteParams",
	},
	"ClientRequestUserVerificationEnroll": {
		"id":     "RequestId",
		"params": "UserVerificationEnrollParams",
	},
	"ClientRequestUserVerificationStatus": {
		"id":     "RequestId",
		"params": "UserVerificationStatusParams",
	},
	"ClientRequestUserVerificationVerify": {
		"id":     "RequestId",
		"params": "UserVerificationVerifyParams",
	},
	"ClientRequestWindowsSandboxReadiness": {
		"id": "RequestId",
	},
	"ClientRequestWindowsSandboxSetupStart": {
		"id":     "RequestId",
		"params": "WindowsSandboxSetupStartParams",
	},
	"CodexErrorInfoActiveTurnNotSteerable": {
		"turnKind": "NonSteerableTurnKind",
	},
	"CollabAgentState": {
		"status": "CollabAgentStatus",
	},
	"CollaborationMode": {
		"mode":     "ModeKind",
		"settings": "Settings",
	},
	"CollaborationModeListResponse": {
		"data": "CollaborationModeMask",
	},
	"CollaborationModeMask": {
		"mode":             "ModeKind",
		"reasoning_effort": "ReasoningEffort",
	},
	"CommandExecOutputDeltaNotification": {
		"stream": "CommandExecOutputStream",
	},
	"CommandExecParams": {
		"sandboxPolicy": "SandboxPolicy",
		"size":          "CommandExecTerminalSize",
	},
	"CommandExecResizeParams": {
		"size": "CommandExecTerminalSize",
	},
	"CommandExecutionApprovalDecisionApplyNetworkPolicyAmendment": {
		"network_policy_amendment": "NetworkPolicyAmendment",
	},
	"CommandExecutionRequestApprovalParams": {
		"additionalPermissions":           "AdditionalPermissionProfile",
		"availableDecisions":              "CommandExecutionApprovalDecision",
		"commandActions":                  "CommandAction",
		"kind":                            "CommandExecutionApprovalKind",
		"networkApprovalContext":          "NetworkApprovalContext",
		"proposedNetworkPolicyAmendments": "NetworkPolicyAmendment",
	},
	"CommandExecutionRequestApprovalResponse": {
		"decision": "CommandExecutionApprovalDecision",
	},
	"ComputerUseConfig": {
		"default_app_access": "AllowDenyRequirement",
		"macos":              "ComputerUseMacosConfig",
		"windows":            "ComputerUseWindowsConfig",
	},
	"ComputerUseMacosConfig": {
		"bundle_ids": "AllowDenyRequirement",
	},
	"ComputerUseMacosRequirements": {
		"bundleIds": "AllowDenyRequirement",
	},
	"ComputerUseRequirements": {
		"defaultAppAccess": "AllowDenyRequirement",
		"macos":            "ComputerUseMacosRequirements",
		"windows":          "ComputerUseWindowsRequirements",
	},
	"ComputerUseWindowsConfig": {
		"aumids": "AllowDenyRequirement",
		"exes":   "ComputerUseWindowsExeConfig",
	},
	"ComputerUseWindowsExeConfig": {
		"access": "AllowDenyRequirement",
	},
	"ComputerUseWindowsExeRequirement": {
		"access": "AllowDenyRequirement",
	},
	"ComputerUseWindowsRequirements": {
		"aumids": "AllowDenyRequirement",
		"exes":   "ComputerUseWindowsExeRequirement",
	},
	"Config": {
		"analytics":                            "AnalyticsConfig",
		"approval_policy":                      "AskForApproval",
		"approvals_reviewer":                   "ApprovalsReviewer",
		"apps":                                 "AppsConfig",
		"browser_use":                          "BrowserUseConfig",
		"computer_use":                         "ComputerUseConfig",
		"forced_chatgpt_workspace_id":          "ForcedChatgptWorkspaceIds",
		"forced_login_method":                  "ForcedLoginMethod",
		"model_auto_compact_token_limit_scope": "AutoCompactTokenLimitScope",
		"model_reasoning_effort":               "ReasoningEffort",
		"model_reasoning_summary":              "ReasoningSummary",
		"model_verbosity":                      "Verbosity",
		"sandbox_mode":                         "SandboxMode",
		"sandbox_workspace_write":              "SandboxWorkspaceWrite",
		"tools":                                "ToolsV2",
		"web_search":                           "WebSearchMode",
	},
	"ConfigBatchWriteParams": {
		"edits": "ConfigEdit",
	},
	"ConfigEdit": {
		"mergeStrategy": "MergeStrategy",
	},
	"ConfigLayer": {
		"name": "ConfigLayerSource",
	},
	"ConfigLayerMetadata": {
		"name": "ConfigLayerSource",
	},
	"ConfigReadResponse": {
		"config":  "Config",
		"layers":  "ConfigLayer",
		"origins": "ConfigLayerMetadata",
	},
	"ConfigRequirements": {
		"allowedApprovalPolicies":              "AskForApproval",
		"allowedApprovalsReviewers":            "ApprovalsReviewer",
		"allowedSandboxModes":                  "SandboxMode",
		"allowedWebSearchModes":                "WebSearchMode",
		"allowedWindowsSandboxImplementations": "WindowsSandboxSetupMode",
		"application":                          "ApplicationRequirements",
		"autoReview":                           "AutoReviewRequirements",
		"browserUse":                           "BrowserUseRequirements",
		"cliAuthCredentialsStore":              "CliAuthCredentialsStoreMode",
		"computerUse":                          "ComputerUseRequirements",
		"enforceResidency":                     "ResidencyRequirement",
		"feedback":                             "FeedbackRequirements",
		"hooks":                                "ManagedHooksRequirements",
		"inAppBrowser":                         "InAppBrowserRequirements",
		"models":                               "ModelsRequirements",
		"network":                              "NetworkRequirements",
	},
	"ConfigRequirementsReadResponse": {
		"requirements": "ConfigRequirements",
	},
	"ConfigValueWriteParams": {
		"mergeStrategy": "MergeStrategy",
	},
	"ConfigWarningNotification": {
		"range": "TextRange",
	},
	"ConfigWriteResponse": {
		"overriddenMetadata": "OverriddenMetadata",
		"status":             "WriteStatus",
	},
	"ConfigurationReasoning": {
		"effort": "ReasoningEffort",
	},
	"ConfiguredHookMatcherGroup": {
		"hooks": "ConfiguredHookHandler",
	},
	"ConnectorMetadata": {
		"toolSummaries": "AppToolSummary",
	},
	"ConsumeAccountRateLimitResetCreditResponse": {
		"outcome": "ConsumeAccountRateLimitResetCreditOutcome",
	},
	"ContentItemInputImage": {
		"detail": "ImageDetail",
	},
	"DynamicToolCallResponse": {
		"contentItems": "DynamicToolCallOutputContentItem",
	},
	"DynamicToolSpecNamespace": {
		"tools": "DynamicToolNamespaceTool",
	},
	"EnvironmentStatusResponse": {
		"status": "EnvironmentStatusKind",
	},
	"ErrorNotification": {
		"error": "TurnError",
	},
	"ExecCommandApprovalParams": {
		"parsedCmd": "ParsedCommand",
	},
	"ExecCommandApprovalResponse": {
		"decision": "ReviewDecision",
	},
	"ExperimentalFeature": {
		"stage": "ExperimentalFeatureStage",
	},
	"ExperimentalFeatureListResponse": {
		"data": "ExperimentalFeature",
	},
	"ExternalAgentConfigDetectResponse": {
		"connectors": "ExternalAgentDetectedConnectorCandidate",
		"items":      "ExternalAgentConfigMigrationItem",
	},
	"ExternalAgentConfigImportCompletedNotification": {
		"itemTypeResults": "ExternalAgentConfigImportTypeResult",
	},
	"ExternalAgentConfigImportHistoriesReadResponse": {
		"connectors": "ExternalAgentImportedConnectorCandidate",
		"data":       "ExternalAgentConfigImportHistory",
	},
	"ExternalAgentConfigImportHistory": {
		"failures":  "ExternalAgentConfigImportItemTypeFailure",
		"successes": "ExternalAgentConfigImportItemTypeSuccess",
	},
	"ExternalAgentConfigImportHistoryRecordParams": {
		"itemTypeResults": "ExternalAgentConfigImportHistoryRecordTypeResultParams",
	},
	"ExternalAgentConfigImportHistoryRecordSuccessParams": {
		"itemType": "ExternalAgentConfigMigrationItemType",
	},
	"ExternalAgentConfigImportHistoryRecordTypeResultParams": {
		"failures":  "ExternalAgentConfigImportItemTypeFailure",
		"itemType":  "ExternalAgentConfigMigrationItemType",
		"successes": "ExternalAgentConfigImportHistoryRecordSuccessParams",
	},
	"ExternalAgentConfigImportItemTypeFailure": {
		"itemType": "ExternalAgentConfigMigrationItemType",
	},
	"ExternalAgentConfigImportItemTypeSuccess": {
		"itemType": "ExternalAgentConfigMigrationItemType",
	},
	"ExternalAgentConfigImportParams": {
		"migrationItems": "ExternalAgentConfigMigrationItem",
	},
	"ExternalAgentConfigImportProgressNotification": {
		"itemTypeResults": "ExternalAgentConfigImportTypeResult",
	},
	"ExternalAgentConfigImportTypeResult": {
		"failures":  "ExternalAgentConfigImportItemTypeFailure",
		"itemType":  "ExternalAgentConfigMigrationItemType",
		"successes": "ExternalAgentConfigImportItemTypeSuccess",
	},
	"ExternalAgentConfigMigrationItem": {
		"details":  "MigrationDetails",
		"itemType": "ExternalAgentConfigMigrationItemType",
	},
	"ExternalAgentDetectedConnectorCandidate": {
		"source": "ExternalAgentDetectedConnectorSource",
	},
	"ExternalAgentImportedConnectorCandidate": {
		"source": "ExternalAgentImportedConnectorSource",
	},
	"FileChangePatchUpdatedNotification": {
		"changes": "FileUpdateChange",
	},
	"FileChangeRequestApprovalResponse": {
		"decision": "FileChangeApprovalDecision",
	},
	"FileSystemPathSpecial": {
		"value": "FileSystemSpecialPath",
	},
	"FileSystemSandboxEntry": {
		"access": "FileSystemAccessMode",
		"path":   "FileSystemPath",
	},
	"FileUpdateChange": {
		"kind": "PatchChangeKind",
	},
	"FsReadDirectoryResponse": {
		"entries": "FsReadDirectoryEntry",
	},
	"FunctionCallOutputContentItemInputImage": {
		"detail": "ImageDetail",
	},
	"FuzzyFileSearchResponse": {
		"files": "FuzzyFileSearchResult",
	},
	"FuzzyFileSearchResult": {
		"match_type": "FuzzyFileSearchMatchType",
	},
	"FuzzyFileSearchSessionUpdatedNotification": {
		"files": "FuzzyFileSearchResult",
	},
	"GetAccountRateLimitsResponse": {
		"rateLimitResetCredits": "RateLimitResetCreditsSummary",
		"rateLimits":            "RateLimitSnapshot",
		"rateLimitsByLimitId":   "RateLimitSnapshot",
	},
	"GetAccountResponse": {
		"account": "Account",
	},
	"GetWorkspaceMessagesResponse": {
		"messages": "WorkspaceMessage",
	},
	"GrantedPermissionProfile": {
		"fileSystem": "AdditionalFileSystemPermissions",
		"network":    "AdditionalNetworkPermissions",
	},
	"GuardianApprovalReview": {
		"riskLevel":         "GuardianRiskLevel",
		"status":            "GuardianApprovalReviewStatus",
		"userAuthorization": "GuardianUserAuthorization",
	},
	"GuardianApprovalReviewActionCommand": {
		"source": "GuardianCommandSource",
	},
	"GuardianApprovalReviewActionExecve": {
		"source": "GuardianCommandSource",
	},
	"GuardianApprovalReviewActionNetworkAccess": {
		"protocol": "NetworkApprovalProtocol",
	},
	"GuardianApprovalReviewActionRequestPermissions": {
		"permissions": "RequestPermissionProfile",
	},
	"HookCompletedNotification": {
		"run": "HookRunSummary",
	},
	"HookMetadata": {
		"eventName":   "HookEventName",
		"source":      "HookSource",
		"trustStatus": "HookTrustStatus",
	},
	"HookOutputEntry": {
		"kind": "HookOutputEntryKind",
	},
	"HookRunSummary": {
		"entries":       "HookOutputEntry",
		"eventName":     "HookEventName",
		"executionMode": "HookExecutionMode",
		"handlerType":   "HookHandlerType",
		"scope":         "HookScope",
		"source":        "HookSource",
		"status":        "HookRunStatus",
	},
	"HookStartedNotification": {
		"run": "HookRunSummary",
	},
	"HooksListEntry": {
		"errors": "HookErrorInfo",
		"hooks":  "HookMetadata",
	},
	"HooksListResponse": {
		"data": "HooksListEntry",
	},
	"InitializeParams": {
		"capabilities": "InitializeCapabilities",
		"clientInfo":   "ClientInfo",
	},
	"ItemCompletedNotification": {
		"item": "ThreadItem",
	},
	"ItemGuardianApprovalReviewCompletedNotification": {
		"action":         "GuardianApprovalReviewAction",
		"decisionSource": "AutoReviewDecisionSource",
		"review":         "GuardianApprovalReview",
	},
	"ItemGuardianApprovalReviewStartedNotification": {
		"action": "GuardianApprovalReviewAction",
		"review": "GuardianApprovalReview",
	},
	"ItemStartedNotification": {
		"item": "ThreadItem",
	},
	"ListMcpServerStatusParams": {
		"detail": "McpServerStatusDetail",
	},
	"ListMcpServerStatusResponse": {
		"data": "McpServerStatus",
	},
	"LoginAccountParamsChatGPT": {
		"appBrand": "LoginAppBrand",
	},
	"ManagedHooksRequirements": {
		"Interrupt":         "ConfiguredHookMatcherGroup",
		"PermissionRequest": "ConfiguredHookMatcherGroup",
		"PostCompact":       "ConfiguredHookMatcherGroup",
		"PostToolUse":       "ConfiguredHookMatcherGroup",
		"PreCompact":        "ConfiguredHookMatcherGroup",
		"PreToolUse":        "ConfiguredHookMatcherGroup",
		"SessionEnd":        "ConfiguredHookMatcherGroup",
		"SessionStart":      "ConfiguredHookMatcherGroup",
		"Stop":              "ConfiguredHookMatcherGroup",
		"SubagentStart":     "ConfiguredHookMatcherGroup",
		"SubagentStop":      "ConfiguredHookMatcherGroup",
		"UserPromptSubmit":  "ConfiguredHookMatcherGroup",
	},
	"MarketplaceUpgradeResponse": {
		"errors": "MarketplaceUpgradeErrorInfo",
	},
	"McpElicitationSchema": {
		"type": "McpElicitationObjectType",
	},
	"McpResourceReadResponse": {
		"contents": "ResourceContent",
	},
	"McpServerElicitationRequestParamsForm": {
		"requestedSchema": "McpElicitationSchema",
	},
	"McpServerElicitationRequestResponse": {
		"action": "McpServerElicitationAction",
	},
	"McpServerEventStreamNotification": {
		"notification": "McpServerEventNotification",
	},
	"McpServerOauthLoginParams": {
		"clientRegistration": "McpServerOauthClientRegistration",
	},
	"McpServerStatus": {
		"authStatus":        "McpAuthStatus",
		"resourceTemplates": "ResourceTemplate",
		"resources":         "Resource",
		"runtimeStatus":     "McpServerConnectionStatus",
		"serverInfo":        "McpServerInfo",
		"tools":             "Tool",
	},
	"McpServerStatusUpdatedNotification": {
		"failureReason": "McpServerStartupFailureReason",
		"status":        "McpServerStartupState",
	},
	"MemoryCitation": {
		"entries": "MemoryCitationEntry",
	},
	"MigrationDetails": {
		"commands":   "CommandMigration",
		"hooks":      "HookMigration",
		"mcpServers": "McpServerMigration",
		"plugins":    "PluginsMigration",
		"sessions":   "SessionMigration",
		"skills":     "SkillMigration",
		"subagents":  "SubagentMigration",
	},
	"MisalignmentErrorDetails": {
		"steer": "MisalignmentSteer",
	},
	"Model": {
		"availabilityNux":           "ModelAvailabilityNux",
		"defaultReasoningEffort":    "ReasoningEffort",
		"inputModalities":           "InputModality",
		"multiAgentVersion":         "MultiAgentVersion",
		"serviceTiers":              "ModelServiceTier",
		"supportedReasoningEfforts": "ReasoningEffortOption",
		"upgradeInfo":               "ModelUpgradeInfo",
	},
	"ModelListResponse": {
		"data": "Model",
	},
	"ModelReroutedNotification": {
		"reason": "ModelRerouteReason",
	},
	"ModelVerificationNotification": {
		"verifications": "ModelVerification",
	},
	"ModelsRequirements": {
		"newThread": "NewThreadModelDefaults",
	},
	"NetworkApprovalContext": {
		"protocol": "NetworkApprovalProtocol",
	},
	"NetworkPolicyAmendment": {
		"action": "NetworkPolicyRuleAction",
	},
	"NetworkRequirements": {
		"domains":     "NetworkDomainPermission",
		"unixSockets": "NetworkUnixSocketPermission",
	},
	"NewThreadModelDefaults": {
		"modelReasoningEffort": "ReasoningEffort",
	},
	"OverriddenMetadata": {
		"overridingLayer": "ConfigLayerMetadata",
	},
	"PermissionsRequestApprovalParams": {
		"permissions": "RequestPermissionProfile",
	},
	"PermissionsRequestApprovalResponse": {
		"permissions": "GrantedPermissionProfile",
		"scope":       "PermissionGrantScope",
	},
	"PluginDetail": {
		"appTemplates":   "AppTemplateSummary",
		"apps":           "AppSummary",
		"hooks":          "PluginHookSummary",
		"scheduledTasks": "ScheduledTaskSummary",
		"skills":         "SkillSummary",
		"summary":        "PluginSummary",
	},
	"PluginHookSummary": {
		"eventName": "HookEventName",
	},
	"PluginInstallResponse": {
		"appsNeedingAuth": "AppSummary",
		"authPolicy":      "PluginAuthPolicy",
	},
	"PluginInstalledResponse": {
		"marketplaceLoadErrors": "MarketplaceLoadErrorInfo",
		"marketplaces":          "PluginMarketplaceEntry",
	},
	"PluginListParams": {
		"marketplaceKinds": "PluginListMarketplaceKind",
	},
	"PluginListResponse": {
		"marketplaceLoadErrors": "MarketplaceLoadErrorInfo",
		"marketplaces":          "PluginMarketplaceEntry",
	},
	"PluginMarketplaceEntry": {
		"interface": "MarketplaceInterface",
		"plugins":   "PluginSummary",
	},
	"PluginReadResponse": {
		"plugin": "PluginDetail",
	},
	"PluginReconcileResponse": {
		"changedPlugins": "PluginReconcileChangedPlugin",
	},
	"PluginSearchParams": {
		"scope": "PluginSearchScope",
	},
	"PluginSearchResponse": {
		"data": "PluginSearchResult",
	},
	"PluginSearchResult": {
		"plugin": "PluginSummary",
	},
	"PluginShareContext": {
		"discoverability": "PluginShareDiscoverability",
		"sharePrincipals": "PluginSharePrincipal",
	},
	"PluginShareListItem": {
		"plugin": "PluginSummary",
	},
	"PluginShareListResponse": {
		"data": "PluginShareListItem",
	},
	"PluginSharePrincipal": {
		"principalType": "PluginSharePrincipalType",
		"role":          "PluginSharePrincipalRole",
	},
	"PluginShareSaveParams": {
		"discoverability": "PluginShareDiscoverability",
		"shareTargets":    "PluginShareTarget",
	},
	"PluginShareTarget": {
		"principalType": "PluginSharePrincipalType",
		"role":          "PluginShareTargetRole",
	},
	"PluginShareUpdateTargetsParams": {
		"discoverability": "PluginShareUpdateDiscoverability",
		"shareTargets":    "PluginShareTarget",
	},
	"PluginShareUpdateTargetsResponse": {
		"discoverability": "PluginShareDiscoverability",
		"principals":      "PluginSharePrincipal",
	},
	"PluginSummary": {
		"authPolicy":          "PluginAuthPolicy",
		"availability":        "PluginAvailability",
		"disabledReason":      "PluginDisabledReason",
		"installPolicy":       "PluginInstallPolicy",
		"installPolicySource": "PluginInstallPolicySource",
		"interface":           "PluginInterface",
		"shareContext":        "PluginShareContext",
		"source":              "PluginSource",
	},
	"ProcessOutputDeltaNotification": {
		"stream": "ProcessOutputStream",
	},
	"ProcessResizePtyParams": {
		"size": "ProcessTerminalSize",
	},
	"ProcessSpawnParams": {
		"size": "ProcessTerminalSize",
	},
	"Project": {
		"roots": "ProjectRoot",
	},
	"ProjectChangedNotification": {
		"changeType": "ProjectChangeType",
	},
	"ProjectCreateParams": {
		"roots": "ProjectRoot",
	},
	"ProjectCreateResponse": {
		"project": "Project",
	},
	"ProjectImportParams": {
		"roots": "ProjectRoot",
	},
	"ProjectImportResponse": {
		"project": "Project",
	},
	"ProjectListParams": {
		"sortDirection": "SortDirection",
		"sortKey":       "ProjectSortKey",
	},
	"ProjectListResponse": {
		"data": "Project",
	},
	"ProjectReadResponse": {
		"project": "Project",
	},
	"ProjectUpdateParams": {
		"roots": "ProjectRoot",
	},
	"ProjectUpdateResponse": {
		"project": "Project",
	},
	"QueuedSubmission": {
		"input": "UserInput",
	},
	"RateLimitResetCredit": {
		"resetType": "RateLimitResetType",
		"status":    "RateLimitResetCreditStatus",
	},
	"RateLimitResetCreditsSummary": {
		"credits": "RateLimitResetCredit",
	},
	"RateLimitSnapshot": {
		"credits":              "CreditsSnapshot",
		"individualLimit":      "SpendControlLimitSnapshot",
		"planType":             "PlanType",
		"primary":              "RateLimitWindow",
		"rateLimitReachedType": "RateLimitReachedType",
		"secondary":            "RateLimitWindow",
	},
	"RawResponseItemCompletedNotification": {
		"item": "ResponseItem",
	},
	"RealtimeVoicesList": {
		"defaultV1": "RealtimeVoice",
		"defaultV2": "RealtimeVoice",
		"v1":        "RealtimeVoice",
		"v2":        "RealtimeVoice",
	},
	"ReasoningEffortOption": {
		"reasoningEffort": "ReasoningEffort",
	},
	"RemoteControlClientsListParams": {
		"order": "RemoteControlClientsListOrder",
	},
	"RemoteControlDisableResponse": {
		"status": "RemoteControlConnectionStatus",
	},
	"RemoteControlEnableResponse": {
		"status": "RemoteControlConnectionStatus",
	},
	"RemoteControlStatusChangedNotification": {
		"status": "RemoteControlConnectionStatus",
	},
	"RemoteControlStatusReadResponse": {
		"status": "RemoteControlConnectionStatus",
	},
	"RequestPermissionProfile": {
		"fileSystem": "AdditionalFileSystemPermissions",
		"network":    "AdditionalNetworkPermissions",
	},
	"ResponseItemAgentMessage": {
		"content": "AgentMessageInputContent",
		"internal_chat_message_metadata_passthrough": "InternalChatMessageMetadataPassthrough",
	},
	"ResponseItemCompaction": {
		"internal_chat_message_metadata_passthrough": "InternalChatMessageMetadataPassthrough",
	},
	"ResponseItemConfigurationUpdate": {
		"reasoning": "ConfigurationReasoning",
	},
	"ResponseItemContextCompaction": {
		"internal_chat_message_metadata_passthrough": "InternalChatMessageMetadataPassthrough",
	},
	"ResponseItemCustomToolCall": {
		"internal_chat_message_metadata_passthrough": "InternalChatMessageMetadataPassthrough",
	},
	"ResponseItemCustomToolCallOutput": {
		"internal_chat_message_metadata_passthrough": "InternalChatMessageMetadataPassthrough",
		"output": "FunctionCallOutputBody",
	},
	"ResponseItemFunctionCall": {
		"internal_chat_message_metadata_passthrough": "InternalChatMessageMetadataPassthrough",
	},
	"ResponseItemFunctionCallOutput": {
		"internal_chat_message_metadata_passthrough": "InternalChatMessageMetadataPassthrough",
		"output": "FunctionCallOutputBody",
	},
	"ResponseItemImageGenerationCall": {
		"internal_chat_message_metadata_passthrough": "InternalChatMessageMetadataPassthrough",
	},
	"ResponseItemLocalShellCall": {
		"action": "LocalShellAction",
		"internal_chat_message_metadata_passthrough": "InternalChatMessageMetadataPassthrough",
		"status": "LocalShellStatus",
	},
	"ResponseItemMessage": {
		"content": "ContentItem",
		"internal_chat_message_metadata_passthrough": "InternalChatMessageMetadataPassthrough",
		"phase": "MessagePhase",
	},
	"ResponseItemReasoning": {
		"content": "ReasoningItemContent",
		"internal_chat_message_metadata_passthrough": "InternalChatMessageMetadataPassthrough",
		"summary": "ReasoningItemReasoningSummary",
	},
	"ResponseItemToolSearchCall": {
		"internal_chat_message_metadata_passthrough": "InternalChatMessageMetadataPassthrough",
	},
	"ResponseItemToolSearchOutput": {
		"internal_chat_message_metadata_passthrough": "InternalChatMessageMetadataPassthrough",
	},
	"ResponseItemWebSearchCall": {
		"action": "ResponsesApiWebSearchAction",
		"internal_chat_message_metadata_passthrough": "InternalChatMessageMetadataPassthrough",
	},
	"ReviewDecisionNetworkPolicyAmendment": {
		"network_policy_amendment": "NetworkPolicyAmendment",
	},
	"ReviewStartParams": {
		"delivery": "ReviewDelivery",
		"target":   "ReviewTarget",
	},
	"ReviewStartResponse": {
		"turn": "Turn",
	},
	"SandboxPolicyExternalSandbox": {
		"networkAccess": "NetworkAccess",
	},
	"ScheduledTaskScheduleHourly": {
		"days": "ScheduledTaskWeekday",
	},
	"ScheduledTaskScheduleWeekly": {
		"days": "ScheduledTaskWeekday",
	},
	"ScheduledTaskSummary": {
		"schedule": "ScheduledTaskSchedule",
	},
	"SelectedCapabilityRoot": {
		"location": "CapabilityRootLocation",
	},
	"SendAddCreditsNudgeEmailParams": {
		"creditType": "AddCreditsNudgeCreditType",
	},
	"SendAddCreditsNudgeEmailResponse": {
		"status": "AddCreditsNudgeEmailStatus",
	},
	"ServerDiagnosticsResponse": {
		"gauges":  "ServerDiagnosticsGauge",
		"process": "ServerDiagnosticsProcess",
	},
	"ServerNotificationAccountLoginCompleted": {
		"params": "AccountLoginCompletedNotification",
	},
	"ServerNotificationAccountRateLimitsUpdated": {
		"params": "AccountRateLimitsUpdatedNotification",
	},
	"ServerNotificationAccountUpdated": {
		"params": "AccountUpdatedNotification",
	},
	"ServerNotificationAppListUpdated": {
		"params": "AppListUpdatedNotification",
	},
	"ServerNotificationAutoApprovalReviewStrictReviewRequired": {
		"params": "StrictReviewRequiredNotification",
	},
	"ServerNotificationCommandExecOutputDelta": {
		"params": "CommandExecOutputDeltaNotification",
	},
	"ServerNotificationConfigWarning": {
		"params": "ConfigWarningNotification",
	},
	"ServerNotificationDeprecationNotice": {
		"params": "DeprecationNoticeNotification",
	},
	"ServerNotificationError": {
		"params": "ErrorNotification",
	},
	"ServerNotificationExternalAgentConfigImportCompleted": {
		"params": "ExternalAgentConfigImportCompletedNotification",
	},
	"ServerNotificationExternalAgentConfigImportProgress": {
		"params": "ExternalAgentConfigImportProgressNotification",
	},
	"ServerNotificationFSChanged": {
		"params": "FsChangedNotification",
	},
	"ServerNotificationFuzzyFileSearchSessionCompleted": {
		"params": "FuzzyFileSearchSessionCompletedNotification",
	},
	"ServerNotificationFuzzyFileSearchSessionUpdated": {
		"params": "FuzzyFileSearchSessionUpdatedNotification",
	},
	"ServerNotificationGuardianWarning": {
		"params": "GuardianWarningNotification",
	},
	"ServerNotificationHookCompleted": {
		"params": "HookCompletedNotification",
	},
	"ServerNotificationHookStarted": {
		"params": "HookStartedNotification",
	},
	"ServerNotificationItemAgentMessageDelta": {
		"params": "AgentMessageDeltaNotification",
	},
	"ServerNotificationItemAutoApprovalReviewCompleted": {
		"params": "ItemGuardianApprovalReviewCompletedNotification",
	},
	"ServerNotificationItemAutoApprovalReviewStarted": {
		"params": "ItemGuardianApprovalReviewStartedNotification",
	},
	"ServerNotificationItemCommandExecutionOutputDelta": {
		"params": "CommandExecutionOutputDeltaNotification",
	},
	"ServerNotificationItemCommandExecutionTerminalInteraction": {
		"params": "TerminalInteractionNotification",
	},
	"ServerNotificationItemCompleted": {
		"params": "ItemCompletedNotification",
	},
	"ServerNotificationItemFileChangeOutputDelta": {
		"params": "FileChangeOutputDeltaNotification",
	},
	"ServerNotificationItemFileChangePatchUpdated": {
		"params": "FileChangePatchUpdatedNotification",
	},
	"ServerNotificationItemMCPToolCallProgress": {
		"params": "McpToolCallProgressNotification",
	},
	"ServerNotificationItemPlanDelta": {
		"params": "PlanDeltaNotification",
	},
	"ServerNotificationItemReasoningSummaryPartAdded": {
		"params": "ReasoningSummaryPartAddedNotification",
	},
	"ServerNotificationItemReasoningSummaryTextDelta": {
		"params": "ReasoningSummaryTextDeltaNotification",
	},
	"ServerNotificationItemReasoningTextDelta": {
		"params": "ReasoningTextDeltaNotification",
	},
	"ServerNotificationItemStarted": {
		"params": "ItemStartedNotification",
	},
	"ServerNotificationMCPServerEventStreamNotification": {
		"params": "McpServerEventStreamNotification",
	},
	"ServerNotificationMCPServerOAuthLoginCompleted": {
		"params": "McpServerOauthLoginCompletedNotification",
	},
	"ServerNotificationMCPServerStartupStatusUpdated": {
		"params": "McpServerStatusUpdatedNotification",
	},
	"ServerNotificationModelProviderAuthRecoveryCompleted": {
		"params": "AuthRecoveryNotification",
	},
	"ServerNotificationModelProviderAuthRecoveryStarted": {
		"params": "AuthRecoveryNotification",
	},
	"ServerNotificationModelRerouted": {
		"params": "ModelReroutedNotification",
	},
	"ServerNotificationModelSafetyBufferingUpdated": {
		"params": "ModelSafetyBufferingUpdatedNotification",
	},
	"ServerNotificationModelVerification": {
		"params": "ModelVerificationNotification",
	},
	"ServerNotificationProcessExited": {
		"params": "ProcessExitedNotification",
	},
	"ServerNotificationProcessOutputDelta": {
		"params": "ProcessOutputDeltaNotification",
	},
	"ServerNotificationProjectChanged": {
		"params": "ProjectChangedNotification",
	},
	"ServerNotificationRemoteControlStatusChanged": {
		"params": "RemoteControlStatusChangedNotification",
	},
	"ServerNotificationServerRequestResolved": {
		"params": "ServerRequestResolvedNotification",
	},
	"ServerNotificationSkillsChanged": {
		"params": "SkillsChangedNotification",
	},
	"ServerNotificationThreadArchived": {
		"params": "ThreadArchivedNotification",
	},
	"ServerNotificationThreadClosed": {
		"params": "ThreadClosedNotification",
	},
	"ServerNotificationThreadCompacted": {
		"params": "ContextCompactedNotification",
	},
	"ServerNotificationThreadDeleted": {
		"params": "ThreadDeletedNotification",
	},
	"ServerNotificationThreadEnvironmentConnected": {
		"params": "EnvironmentConnectionNotification",
	},
	"ServerNotificationThreadEnvironmentDisconnected": {
		"params": "EnvironmentConnectionNotification",
	},
	"ServerNotificationThreadGoalCleared": {
		"params": "ThreadGoalClearedNotification",
	},
	"ServerNotificationThreadGoalUpdated": {
		"params": "ThreadGoalUpdatedNotification",
	},
	"ServerNotificationThreadNameUpdated": {
		"params": "ThreadNameUpdatedNotification",
	},
	"ServerNotificationThreadProjectUpdated": {
		"params": "ThreadProjectUpdatedNotification",
	},
	"ServerNotificationThreadQueueChanged": {
		"params": "ThreadQueueChangedNotification",
	},
	"ServerNotificationThreadRealtimeClosed": {
		"params": "ThreadRealtimeClosedNotification",
	},
	"ServerNotificationThreadRealtimeError": {
		"params": "ThreadRealtimeErrorNotification",
	},
	"ServerNotificationThreadRealtimeItemAdded": {
		"params": "ThreadRealtimeItemAddedNotification",
	},
	"ServerNotificationThreadRealtimeItemCompleted": {
		"params": "ThreadRealtimeItemCompletedNotification",
	},
	"ServerNotificationThreadRealtimeItemStarted": {
		"params": "ThreadRealtimeItemStartedNotification",
	},
	"ServerNotificationThreadRealtimeItemTranscriptDelta": {
		"params": "ThreadRealtimeItemTranscriptDeltaNotification",
	},
	"ServerNotificationThreadRealtimeOutputAudioDelta": {
		"params": "ThreadRealtimeOutputAudioDeltaNotification",
	},
	"ServerNotificationThreadRealtimeSDP": {
		"params": "ThreadRealtimeSdpNotification",
	},
	"ServerNotificationThreadRealtimeStarted": {
		"params": "ThreadRealtimeStartedNotification",
	},
	"ServerNotificationThreadRealtimeTranscriptDelta": {
		"params": "ThreadRealtimeTranscriptDeltaNotification",
	},
	"ServerNotificationThreadRealtimeTranscriptDone": {
		"params": "ThreadRealtimeTranscriptDoneNotification",
	},
	"ServerNotificationThreadReverted": {
		"params": "ThreadRevertedNotification",
	},
	"ServerNotificationThreadSettingsUpdated": {
		"params": "ThreadSettingsUpdatedNotification",
	},
	"ServerNotificationThreadStarted": {
		"params": "ThreadStartedNotification",
	},
	"ServerNotificationThreadStatusChanged": {
		"params": "ThreadStatusChangedNotification",
	},
	"ServerNotificationThreadTokenUsageUpdated": {
		"params": "ThreadTokenUsageUpdatedNotification",
	},
	"ServerNotificationThreadUnarchived": {
		"params": "ThreadUnarchivedNotification",
	},
	"ServerNotificationTurnCompleted": {
		"params": "TurnCompletedNotification",
	},
	"ServerNotificationTurnDiffUpdated": {
		"params": "TurnDiffUpdatedNotification",
	},
	"ServerNotificationTurnModerationMetadata": {
		"params": "TurnModerationMetadataNotification",
	},
	"ServerNotificationTurnPlanUpdated": {
		"params": "TurnPlanUpdatedNotification",
	},
	"ServerNotificationTurnStarted": {
		"params": "TurnStartedNotification",
	},
	"ServerNotificationWarning": {
		"params": "WarningNotification",
	},
	"ServerNotificationWindowsSandboxSetupCompleted": {
		"params": "WindowsSandboxSetupCompletedNotification",
	},
	"ServerNotificationWindowsWorldWritableWarning": {
		"params": "WindowsWorldWritableWarningNotification",
	},
	"ServerRequestAccountChatGPTAuthTokensRefresh": {
		"id":     "RequestId",
		"params": "ChatgptAuthTokensRefreshParams",
	},
	"ServerRequestApplyPatchApproval": {
		"id":     "RequestId",
		"params": "ApplyPatchApprovalParams",
	},
	"ServerRequestAttestationGenerate": {
		"id":     "RequestId",
		"params": "AttestationGenerateParams",
	},
	"ServerRequestCurrentTimeRead": {
		"id":     "RequestId",
		"params": "CurrentTimeReadParams",
	},
	"ServerRequestExecCommandApproval": {
		"id":     "RequestId",
		"params": "ExecCommandApprovalParams",
	},
	"ServerRequestItemCommandExecutionRequestApproval": {
		"id":     "RequestId",
		"params": "CommandExecutionRequestApprovalParams",
	},
	"ServerRequestItemFileChangeRequestApproval": {
		"id":     "RequestId",
		"params": "FileChangeRequestApprovalParams",
	},
	"ServerRequestItemPermissionsRequestApproval": {
		"id":     "RequestId",
		"params": "PermissionsRequestApprovalParams",
	},
	"ServerRequestItemToolCall": {
		"id":     "RequestId",
		"params": "DynamicToolCallParams",
	},
	"ServerRequestItemToolRequestUserInput": {
		"id":     "RequestId",
		"params": "ToolRequestUserInputParams",
	},
	"ServerRequestMCPServerElicitationRequest": {
		"id":     "RequestId",
		"params": "McpServerElicitationRequestParams",
	},
	"ServerRequestResolvedNotification": {
		"requestId": "RequestId",
	},
	"SessionSourceSubAgent": {
		"subAgent": "SubAgentSource",
	},
	"Settings": {
		"reasoning_effort": "ReasoningEffort",
	},
	"SkillDependencies": {
		"tools": "SkillToolDependency",
	},
	"SkillMetadata": {
		"dependencies": "SkillDependencies",
		"interface":    "SkillInterface",
		"scope":        "SkillScope",
	},
	"SkillSummary": {
		"interface": "SkillInterface",
	},
	"SkillsListEntry": {
		"errors": "SkillErrorInfo",
		"skills": "SkillMetadata",
	},
	"SkillsListResponse": {
		"data": "SkillsListEntry",
	},
	"TextElement": {
		"byteRange": "ByteRange",
	},
	"TextRange": {
		"end":   "TextPosition",
		"start": "TextPosition",
	},
	"Thread": {
		"environments":    "ThreadEnvironment",
		"extra":           "ThreadExtra",
		"gitInfo":         "GitInfo",
		"historyMode":     "ThreadHistoryMode",
		"reasoningEffort": "ReasoningEffort",
		"section":         "ThreadSection",
		"source":          "SessionSource",
		"status":          "ThreadStatus",
		"threadSource":    "ThreadSource",
		"turns":           "Turn",
	},
	"ThreadForkParams": {
		"approvalPolicy":    "AskForApproval",
		"approvalsReviewer": "ApprovalsReviewer",
		"sandbox":           "SandboxMode",
		"threadSource":      "ThreadSource",
	},
	"ThreadForkResponse": {
		"activePermissionProfile": "ActivePermissionProfile",
		"approvalPolicy":          "AskForApproval",
		"approvalsReviewer":       "ApprovalsReviewer",
		"multiAgentMode":          "MultiAgentMode",
		"reasoningEffort":         "ReasoningEffort",
		"sandbox":                 "SandboxPolicy",
		"thread":                  "Thread",
	},
	"ThreadGoal": {
		"status": "ThreadGoalStatus",
	},
	"ThreadGoalGetResponse": {
		"goal": "ThreadGoal",
	},
	"ThreadGoalSetParams": {
		"status": "ThreadGoalStatus",
	},
	"ThreadGoalSetResponse": {
		"goal": "ThreadGoal",
	},
	"ThreadGoalUpdatedNotification": {
		"goal": "ThreadGoal",
	},
	"ThreadItemAgentMessage": {
		"delivery":       "AgentMessageDelivery",
		"memoryCitation": "MemoryCitation",
		"phase":          "MessagePhase",
		"questions":      "AsyncUserInputQuestion",
	},
	"ThreadItemCollabAgentToolCall": {
		"agentsStates":    "CollabAgentState",
		"reasoningEffort": "ReasoningEffort",
		"status":          "CollabAgentToolCallStatus",
		"tool":            "CollabAgentTool",
	},
	"ThreadItemCommandExecution": {
		"commandActions": "CommandAction",
		"source":         "CommandExecutionSource",
		"status":         "CommandExecutionStatus",
	},
	"ThreadItemDynamicToolCall": {
		"contentItems": "DynamicToolCallOutputContentItem",
		"status":       "DynamicToolCallStatus",
	},
	"ThreadItemEntry": {
		"item": "ThreadItem",
	},
	"ThreadItemFileChange": {
		"changes": "FileUpdateChange",
		"status":  "PatchApplyStatus",
	},
	"ThreadItemFunctionCallOutput": {
		"output": "FunctionCallOutputBody",
	},
	"ThreadItemHookPrompt": {
		"fragments": "HookPromptFragment",
	},
	"ThreadItemImageGeneration": {
		"failure": "ImageGenerationFailure",
	},
	"ThreadItemMCPToolCall": {
		"appContext": "McpToolCallAppContext",
		"error":      "McpToolCallError",
		"result":     "McpToolCallResult",
		"status":     "McpToolCallStatus",
	},
	"ThreadItemSubAgentActivity": {
		"kind": "SubAgentActivityKind",
	},
	"ThreadItemUserMessage": {
		"content": "UserInput",
	},
	"ThreadItemWebSearch": {
		"action": "WebSearchAction",
	},
	"ThreadItemsListParams": {
		"sortDirection": "SortDirection",
	},
	"ThreadItemsListResponse": {
		"data": "ThreadItemEntry",
	},
	"ThreadListParams": {
		"cwd":           "ThreadListCwdFilter",
		"sortDirection": "SortDirection",
		"sortKey":       "ThreadSortKey",
		"sourceKinds":   "ThreadSourceKind",
	},
	"ThreadListResponse": {
		"data": "Thread",
	},
	"ThreadMemoryModeSetParams": {
		"mode": "ThreadMemoryMode",
	},
	"ThreadMetadataUpdateParams": {
		"gitInfo": "ThreadMetadataGitInfoUpdateParams",
	},
	"ThreadMetadataUpdateResponse": {
		"thread": "Thread",
	},
	"ThreadQueueAddParams": {
		"input": "UserInput",
	},
	"ThreadQueueAddResponse": {
		"queuedSubmission": "QueuedSubmission",
	},
	"ThreadQueueListResponse": {
		"data": "QueuedSubmission",
	},
	"ThreadQueueStartResponse": {
		"turn": "Turn",
	},
	"ThreadQueueUpdateParams": {
		"input": "UserInput",
	},
	"ThreadQueueUpdateResponse": {
		"queuedSubmission": "QueuedSubmission",
	},
	"ThreadReadResponse": {
		"thread": "Thread",
	},
	"ThreadRealtimeAppendAudioParams": {
		"audio": "ThreadRealtimeAudioChunk",
	},
	"ThreadRealtimeAppendTextParams": {
		"role": "ConversationTextRole",
	},
	"ThreadRealtimeInitialItem": {
		"role": "ConversationTextRole",
	},
	"ThreadRealtimeListVoicesResponse": {
		"voices": "RealtimeVoicesList",
	},
	"ThreadRealtimeOutputAudioDeltaNotification": {
		"audio": "ThreadRealtimeAudioChunk",
	},
	"ThreadRealtimeStartParams": {
		"codexResponseHandoffMode": "CodexResponseHandoffMode",
		"initialItems":             "ThreadRealtimeInitialItem",
		"outputModality":           "RealtimeOutputModality",
		"transport":                "ThreadRealtimeStartTransport",
		"version":                  "RealtimeConversationVersion",
		"voice":                    "RealtimeVoice",
	},
	"ThreadRealtimeStartedNotification": {
		"version": "RealtimeConversationVersion",
	},
	"ThreadResumeInitialTurnsPageParams": {
		"itemsView":     "TurnItemsView",
		"sortDirection": "SortDirection",
	},
	"ThreadResumeParams": {
		"approvalPolicy":    "AskForApproval",
		"approvalsReviewer": "ApprovalsReviewer",
		"history":           "ResponseItem",
		"initialTurnsPage":  "ThreadResumeInitialTurnsPageParams",
		"personality":       "Personality",
		"sandbox":           "SandboxMode",
	},
	"ThreadResumeResponse": {
		"activePermissionProfile": "ActivePermissionProfile",
		"approvalPolicy":          "AskForApproval",
		"approvalsReviewer":       "ApprovalsReviewer",
		"initialTurnsPage":        "TurnsPage",
		"multiAgentMode":          "MultiAgentMode",
		"reasoningEffort":         "ReasoningEffort",
		"sandbox":                 "SandboxPolicy",
		"thread":                  "Thread",
	},
	"ThreadRevertResponse": {
		"thread": "Thread",
	},
	"ThreadRollbackResponse": {
		"thread": "Thread",
	},
	"ThreadSearchOccurrence": {
		"snippetMatchRange": "ThreadSearchTextRange",
	},
	"ThreadSearchOccurrencesResponse": {
		"data": "ThreadSearchOccurrence",
	},
	"ThreadSearchParams": {
		"sortDirection": "SortDirection",
		"sortKey":       "ThreadSearchSortKey",
		"sourceKinds":   "ThreadSourceKind",
	},
	"ThreadSection": {
		"appearance": "ThreadSectionAppearance",
	},
	"ThreadSectionCreateParams": {
		"appearance": "ThreadSectionAppearance",
	},
	"ThreadSectionCreateResponse": {
		"section": "ThreadSection",
	},
	"ThreadSectionListResponse": {
		"data": "ThreadSection",
	},
	"ThreadSectionUpdateParams": {
		"appearance": "ThreadSectionAppearance",
	},
	"ThreadSectionUpdateResponse": {
		"section": "ThreadSection",
	},
	"ThreadSettings": {
		"activePermissionProfile": "ActivePermissionProfile",
		"approvalPolicy":          "AskForApproval",
		"approvalsReviewer":       "ApprovalsReviewer",
		"collaborationMode":       "CollaborationMode",
		"effort":                  "ReasoningEffort",
		"multiAgentMode":          "MultiAgentMode",
		"personality":             "Personality",
		"sandboxPolicy":           "SandboxPolicy",
		"summary":                 "ReasoningSummary",
	},
	"ThreadSettingsUpdateParams": {
		"approvalPolicy":    "AskForApproval",
		"approvalsReviewer": "ApprovalsReviewer",
		"collaborationMode": "CollaborationMode",
		"effort":            "ReasoningEffort",
		"multiAgentMode":    "MultiAgentMode",
		"personality":       "Personality",
		"sandboxPolicy":     "SandboxPolicy",
		"summary":           "ReasoningSummary",
	},
	"ThreadSettingsUpdatedNotification": {
		"threadSettings": "ThreadSettings",
	},
	"ThreadStartParams": {
		"approvalPolicy":          "AskForApproval",
		"approvalsReviewer":       "ApprovalsReviewer",
		"dynamicTools":            "DynamicToolSpec",
		"environments":            "TurnEnvironmentParams",
		"historyMode":             "ThreadHistoryMode",
		"multiAgentMode":          "MultiAgentMode",
		"personality":             "Personality",
		"sandbox":                 "SandboxMode",
		"selectedCapabilityRoots": "SelectedCapabilityRoot",
		"sessionStartSource":      "ThreadStartSource",
		"threadSource":            "ThreadSource",
	},
	"ThreadStartResponse": {
		"activePermissionProfile": "ActivePermissionProfile",
		"approvalPolicy":          "AskForApproval",
		"approvalsReviewer":       "ApprovalsReviewer",
		"multiAgentMode":          "MultiAgentMode",
		"reasoningEffort":         "ReasoningEffort",
		"sandbox":                 "SandboxPolicy",
		"thread":                  "Thread",
	},
	"ThreadStartedNotification": {
		"thread": "Thread",
	},
	"ThreadStatusActive": {
		"activeFlags": "ThreadActiveFlag",
	},
	"ThreadStatusChangedNotification": {
		"status": "ThreadStatus",
	},
	"ThreadTokenUsage": {
		"last":  "TokenUsageBreakdown",
		"total": "TokenUsageBreakdown",
	},
	"ThreadTokenUsageUpdatedNotification": {
		"tokenUsage": "ThreadTokenUsage",
	},
	"ThreadTurnsListParams": {
		"itemsView":     "TurnItemsView",
		"sortDirection": "SortDirection",
	},
	"ThreadTurnsListResponse": {
		"data": "Turn",
	},
	"ThreadUnarchiveResponse": {
		"thread": "Thread",
	},
	"ThreadUnsubscribeResponse": {
		"status": "ThreadUnsubscribeStatus",
	},
	"ToolRequestUserInputParams": {
		"questions": "ToolRequestUserInputQuestion",
	},
	"ToolRequestUserInputQuestion": {
		"options": "ToolRequestUserInputOption",
	},
	"ToolRequestUserInputResponse": {
		"answers": "ToolRequestUserInputAnswer",
	},
	"ToolsV2": {
		"web_search": "WebSearchToolConfig",
	},
	"Turn": {
		"error":     "TurnError",
		"items":     "ThreadItem",
		"itemsView": "TurnItemsView",
		"status":    "TurnStatus",
	},
	"TurnCompletedNotification": {
		"turn": "Turn",
	},
	"TurnError": {
		"codexErrorInfo": "CodexErrorInfo",
		"misalignment":   "MisalignmentErrorDetails",
	},
	"TurnPlanStep": {
		"status": "TurnPlanStepStatus",
	},
	"TurnPlanUpdatedNotification": {
		"plan": "TurnPlanStep",
	},
	"TurnSettingsUpdateParams": {
		"approvalsReviewer": "ApprovalsReviewer",
		"effort":            "ReasoningEffort",
		"summary":           "ReasoningSummary",
	},
	"TurnSettingsUpdateResponse": {
		"status": "TurnSettingsUpdateStatus",
	},
	"TurnStartParams": {
		"additionalContext":  "AdditionalContextEntry",
		"approvalPolicy":     "AskForApproval",
		"approvalsReviewer":  "ApprovalsReviewer",
		"collaborationMode":  "CollaborationMode",
		"cyberAccessProgram": "CyberAccessProgram",
		"effort":             "ReasoningEffort",
		"environments":       "TurnEnvironmentParams",
		"input":              "UserInput",
		"multiAgentMode":     "MultiAgentMode",
		"outputSchema":       "OutputSchema",
		"personality":        "Personality",
		"sandboxPolicy":      "SandboxPolicy",
		"summary":            "ReasoningSummary",
		"toolOutput":         "TurnToolOutput",
	},
	"TurnStartResponse": {
		"turn": "Turn",
	},
	"TurnStartedNotification": {
		"turn": "Turn",
	},
	"TurnSteerParams": {
		"additionalContext": "AdditionalContextEntry",
		"input":             "UserInput",
	},
	"TurnToolOutput": {
		"output": "FunctionCallOutputBody",
	},
	"TurnsPage": {
		"data": "Turn",
	},
	"UserInputImage": {
		"detail": "ImageDetail",
	},
	"UserInputLocalImage": {
		"detail": "ImageDetail",
	},
	"UserInputText": {
		"text_elements": "TextElement",
	},
	"UserVerificationErrorDetailsCancelled": {
		"reason": "UserVerificationCancellationReason",
	},
	"UserVerificationErrorDetailsFailed": {
		"reason": "UserVerificationFailureReason",
	},
	"UserVerificationErrorDetailsInvalidRequest": {
		"reason": "UserVerificationInvalidRequestReason",
	},
	"UserVerificationErrorDetailsUnavailable": {
		"reason": "UserVerificationUnavailableReason",
	},
	"UserVerificationRpcError": {
		"data": "UserVerificationErrorDetails",
	},
	"UserVerificationStatusResponse": {
		"unavailableReason": "UserVerificationUnavailableReason",
	},
	"UserVerificationVerifyResponse": {
		"proof": "UserVerificationProof",
	},
	"WebSearchToolConfig": {
		"context_size": "WebSearchContextSize",
		"location":     "WebSearchLocation",
	},
	"WindowsSandboxReadinessResponse": {
		"status": "WindowsSandboxReadiness",
	},
	"WindowsSandboxSetupCompletedNotification": {
		"mode": "WindowsSandboxSetupMode",
	},
	"WindowsSandboxSetupStartParams": {
		"mode": "WindowsSandboxSetupMode",
	},
	"WorkspaceMessage": {
		"messageType": "WorkspaceMessageType",
	},
}
