// Code generated by scripts/codexsdk_generate_sdk_surface.py; DO NOT EDIT.

package codexsdk

import (
	"context"

	"github.com/ronhuafeng/codexsdk-go/codexsdk/protocolv2"
)

// Accounts is an opaque generated facade for exact Codex operations.
type Accounts struct {
	client *Client
}

func (c *Client) Accounts() Accounts {
	return Accounts{client: c}
}

// Apps is an opaque generated facade for exact Codex operations.
type Apps struct {
	client *Client
}

func (c *Client) Apps() Apps {
	return Apps{client: c}
}

// CollaborationModes is an opaque generated facade for exact Codex operations.
type CollaborationModes struct {
	client *Client
}

func (c *Client) CollaborationModes() CollaborationModes {
	return CollaborationModes{client: c}
}

// Commands is an opaque generated facade for exact Codex operations.
type Commands struct {
	client *Client
}

func (c *Client) Commands() Commands {
	return Commands{client: c}
}

// Config is an opaque generated facade for exact Codex operations.
type Config struct {
	client *Client
}

func (c *Client) Config() Config {
	return Config{client: c}
}

// ConfigRequirements is an opaque generated facade for exact Codex operations.
type ConfigRequirements struct {
	client *Client
}

func (c *Client) ConfigRequirements() ConfigRequirements {
	return ConfigRequirements{client: c}
}

// Environments is an opaque generated facade for exact Codex operations.
type Environments struct {
	client *Client
}

func (c *Client) Environments() Environments {
	return Environments{client: c}
}

// ExperimentalFeatures is an opaque generated facade for exact Codex operations.
type ExperimentalFeatures struct {
	client *Client
}

func (c *Client) ExperimentalFeatures() ExperimentalFeatures {
	return ExperimentalFeatures{client: c}
}

// ExternalAgentConfigs is an opaque generated facade for exact Codex operations.
type ExternalAgentConfigs struct {
	client *Client
}

func (c *Client) ExternalAgentConfigs() ExternalAgentConfigs {
	return ExternalAgentConfigs{client: c}
}

// FS is an opaque generated facade for exact Codex operations.
type FS struct {
	client *Client
}

func (c *Client) FS() FS {
	return FS{client: c}
}

// Feedback is an opaque generated facade for exact Codex operations.
type Feedback struct {
	client *Client
}

func (c *Client) Feedback() Feedback {
	return Feedback{client: c}
}

// FuzzyFileSearch is an opaque generated facade for exact Codex operations.
type FuzzyFileSearch struct {
	client *Client
}

func (c *Client) FuzzyFileSearch() FuzzyFileSearch {
	return FuzzyFileSearch{client: c}
}

// Hooks is an opaque generated facade for exact Codex operations.
type Hooks struct {
	client *Client
}

func (c *Client) Hooks() Hooks {
	return Hooks{client: c}
}

// MCPServerStatus is an opaque generated facade for exact Codex operations.
type MCPServerStatus struct {
	client *Client
}

func (c *Client) MCPServerStatus() MCPServerStatus {
	return MCPServerStatus{client: c}
}

// MCPServers is an opaque generated facade for exact Codex operations.
type MCPServers struct {
	client *Client
}

func (c *Client) MCPServers() MCPServers {
	return MCPServers{client: c}
}

// Marketplace is an opaque generated facade for exact Codex operations.
type Marketplace struct {
	client *Client
}

func (c *Client) Marketplace() Marketplace {
	return Marketplace{client: c}
}

// Memory is an opaque generated facade for exact Codex operations.
type Memory struct {
	client *Client
}

func (c *Client) Memory() Memory {
	return Memory{client: c}
}

// Mock is an opaque generated facade for exact Codex operations.
type Mock struct {
	client *Client
}

func (c *Client) Mock() Mock {
	return Mock{client: c}
}

// ModelProviders is an opaque generated facade for exact Codex operations.
type ModelProviders struct {
	client *Client
}

func (c *Client) ModelProviders() ModelProviders {
	return ModelProviders{client: c}
}

// Models is an opaque generated facade for exact Codex operations.
type Models struct {
	client *Client
}

func (c *Client) Models() Models {
	return Models{client: c}
}

// Plugins is an opaque generated facade for exact Codex operations.
type Plugins struct {
	client *Client
}

func (c *Client) Plugins() Plugins {
	return Plugins{client: c}
}

// Processes is an opaque generated facade for exact Codex operations.
type Processes struct {
	client *Client
}

func (c *Client) Processes() Processes {
	return Processes{client: c}
}

// RemoteControl is an opaque generated facade for exact Codex operations.
type RemoteControl struct {
	client *Client
}

func (c *Client) RemoteControl() RemoteControl {
	return RemoteControl{client: c}
}

// Reviews is an opaque generated facade for exact Codex operations.
type Reviews struct {
	client *Client
}

func (c *Client) Reviews() Reviews {
	return Reviews{client: c}
}

// Skills is an opaque generated facade for exact Codex operations.
type Skills struct {
	client *Client
}

func (c *Client) Skills() Skills {
	return Skills{client: c}
}

// Threads is an opaque generated facade for exact Codex operations.
type Threads struct {
	client *Client
}

func (c *Client) Threads() Threads {
	return Threads{client: c}
}

// Turns is an opaque generated facade for exact Codex operations.
type Turns struct {
	client *Client
}

func (c *Client) Turns() Turns {
	return Turns{client: c}
}

// WindowsSandbox is an opaque generated facade for exact Codex operations.
type WindowsSandbox struct {
	client *Client
}

func (c *Client) WindowsSandbox() WindowsSandbox {
	return WindowsSandbox{client: c}
}

func (f Accounts) LoginCancel(ctx context.Context, params protocolv2.CancelLoginAccountParams) (protocolv2.CancelLoginAccountResponse, error) {
	var response protocolv2.CancelLoginAccountResponse
	if err := f.client.callProtocol(ctx, protocolv2.MethodAccountLoginCancel, params, &response); err != nil {
		return protocolv2.CancelLoginAccountResponse{}, err
	}
	return response, nil
}

func (f Accounts) LoginStart(ctx context.Context, params protocolv2.LoginAccountParams) (protocolv2.LoginAccountResponse, error) {
	var response protocolv2.LoginAccountResponse
	if err := f.client.callProtocol(ctx, protocolv2.MethodAccountLoginStart, params, &response); err != nil {
		return protocolv2.LoginAccountResponse{}, err
	}
	return response, nil
}

func (f Accounts) Logout(ctx context.Context) (protocolv2.LogoutAccountResponse, error) {
	var response protocolv2.LogoutAccountResponse
	if err := f.client.callProtocolNoParams(ctx, protocolv2.MethodAccountLogout, &response); err != nil {
		return protocolv2.LogoutAccountResponse{}, err
	}
	return response, nil
}

func (f Accounts) RateLimitResetCreditConsume(ctx context.Context, params protocolv2.ConsumeAccountRateLimitResetCreditParams) (protocolv2.ConsumeAccountRateLimitResetCreditResponse, error) {
	var response protocolv2.ConsumeAccountRateLimitResetCreditResponse
	if err := f.client.callProtocol(ctx, protocolv2.MethodAccountRateLimitResetCreditConsume, params, &response); err != nil {
		return protocolv2.ConsumeAccountRateLimitResetCreditResponse{}, err
	}
	return response, nil
}

func (f Accounts) RateLimitsRead(ctx context.Context) (protocolv2.GetAccountRateLimitsResponse, error) {
	var response protocolv2.GetAccountRateLimitsResponse
	if err := f.client.callProtocolNoParams(ctx, protocolv2.MethodAccountRateLimitsRead, &response); err != nil {
		return protocolv2.GetAccountRateLimitsResponse{}, err
	}
	return response, nil
}

func (f Accounts) Read(ctx context.Context, params protocolv2.GetAccountParams) (protocolv2.GetAccountResponse, error) {
	var response protocolv2.GetAccountResponse
	if err := f.client.callProtocol(ctx, protocolv2.MethodAccountRead, params, &response); err != nil {
		return protocolv2.GetAccountResponse{}, err
	}
	return response, nil
}

func (f Accounts) SendAddCreditsNudgeEmail(ctx context.Context, params protocolv2.SendAddCreditsNudgeEmailParams) (protocolv2.SendAddCreditsNudgeEmailResponse, error) {
	var response protocolv2.SendAddCreditsNudgeEmailResponse
	if err := f.client.callProtocol(ctx, protocolv2.MethodAccountSendAddCreditsNudgeEmail, params, &response); err != nil {
		return protocolv2.SendAddCreditsNudgeEmailResponse{}, err
	}
	return response, nil
}

func (f Accounts) WorkspaceMessagesRead(ctx context.Context) (protocolv2.GetWorkspaceMessagesResponse, error) {
	var response protocolv2.GetWorkspaceMessagesResponse
	if err := f.client.callProtocolNoParams(ctx, protocolv2.MethodAccountWorkspaceMessagesRead, &response); err != nil {
		return protocolv2.GetWorkspaceMessagesResponse{}, err
	}
	return response, nil
}

func (f Apps) List(ctx context.Context, params protocolv2.AppsListParams) (protocolv2.AppsListResponse, error) {
	var response protocolv2.AppsListResponse
	if err := f.client.callProtocol(ctx, protocolv2.MethodAppList, params, &response); err != nil {
		return protocolv2.AppsListResponse{}, err
	}
	return response, nil
}

func (f CollaborationModes) List(ctx context.Context, params protocolv2.CollaborationModeListParams) (protocolv2.CollaborationModeListResponse, error) {
	var response protocolv2.CollaborationModeListResponse
	if err := f.client.callProtocol(ctx, protocolv2.MethodCollaborationModeList, params, &response); err != nil {
		return protocolv2.CollaborationModeListResponse{}, err
	}
	return response, nil
}

func (f Commands) Exec(ctx context.Context, params protocolv2.CommandExecParams) (protocolv2.CommandExecResponse, error) {
	var response protocolv2.CommandExecResponse
	if err := f.client.callProtocol(ctx, protocolv2.MethodCommandExec, params, &response); err != nil {
		return protocolv2.CommandExecResponse{}, err
	}
	return response, nil
}

func (f Commands) ExecResize(ctx context.Context, params protocolv2.CommandExecResizeParams) (protocolv2.CommandExecResizeResponse, error) {
	var response protocolv2.CommandExecResizeResponse
	if err := f.client.callProtocol(ctx, protocolv2.MethodCommandExecResize, params, &response); err != nil {
		return protocolv2.CommandExecResizeResponse{}, err
	}
	return response, nil
}

func (f Commands) ExecTerminate(ctx context.Context, params protocolv2.CommandExecTerminateParams) (protocolv2.CommandExecTerminateResponse, error) {
	var response protocolv2.CommandExecTerminateResponse
	if err := f.client.callProtocol(ctx, protocolv2.MethodCommandExecTerminate, params, &response); err != nil {
		return protocolv2.CommandExecTerminateResponse{}, err
	}
	return response, nil
}

func (f Commands) ExecWrite(ctx context.Context, params protocolv2.CommandExecWriteParams) (protocolv2.CommandExecWriteResponse, error) {
	var response protocolv2.CommandExecWriteResponse
	if err := f.client.callProtocol(ctx, protocolv2.MethodCommandExecWrite, params, &response); err != nil {
		return protocolv2.CommandExecWriteResponse{}, err
	}
	return response, nil
}

func (f Config) BatchWrite(ctx context.Context, params protocolv2.ConfigBatchWriteParams) (protocolv2.ConfigWriteResponse, error) {
	var response protocolv2.ConfigWriteResponse
	if err := f.client.callProtocol(ctx, protocolv2.MethodConfigBatchWrite, params, &response); err != nil {
		return protocolv2.ConfigWriteResponse{}, err
	}
	return response, nil
}

func (f Config) MCPServerReload(ctx context.Context) (protocolv2.McpServerRefreshResponse, error) {
	var response protocolv2.McpServerRefreshResponse
	if err := f.client.callProtocolNoParams(ctx, protocolv2.MethodConfigMCPServerReload, &response); err != nil {
		return protocolv2.McpServerRefreshResponse{}, err
	}
	return response, nil
}

func (f Config) Read(ctx context.Context, params protocolv2.ConfigReadParams) (protocolv2.ConfigReadResponse, error) {
	var response protocolv2.ConfigReadResponse
	if err := f.client.callProtocol(ctx, protocolv2.MethodConfigRead, params, &response); err != nil {
		return protocolv2.ConfigReadResponse{}, err
	}
	return response, nil
}

func (f Config) ValueWrite(ctx context.Context, params protocolv2.ConfigValueWriteParams) (protocolv2.ConfigWriteResponse, error) {
	var response protocolv2.ConfigWriteResponse
	if err := f.client.callProtocol(ctx, protocolv2.MethodConfigValueWrite, params, &response); err != nil {
		return protocolv2.ConfigWriteResponse{}, err
	}
	return response, nil
}

func (f ConfigRequirements) Read(ctx context.Context) (protocolv2.ConfigRequirementsReadResponse, error) {
	var response protocolv2.ConfigRequirementsReadResponse
	if err := f.client.callProtocolNoParams(ctx, protocolv2.MethodConfigRequirementsRead, &response); err != nil {
		return protocolv2.ConfigRequirementsReadResponse{}, err
	}
	return response, nil
}

func (f Environments) Add(ctx context.Context, params protocolv2.EnvironmentAddParams) (protocolv2.EnvironmentAddResponse, error) {
	var response protocolv2.EnvironmentAddResponse
	if err := f.client.callProtocol(ctx, protocolv2.MethodEnvironmentAdd, params, &response); err != nil {
		return protocolv2.EnvironmentAddResponse{}, err
	}
	return response, nil
}

func (f ExperimentalFeatures) EnablementSet(ctx context.Context, params protocolv2.ExperimentalFeatureEnablementSetParams) (protocolv2.ExperimentalFeatureEnablementSetResponse, error) {
	var response protocolv2.ExperimentalFeatureEnablementSetResponse
	if err := f.client.callProtocol(ctx, protocolv2.MethodExperimentalFeatureEnablementSet, params, &response); err != nil {
		return protocolv2.ExperimentalFeatureEnablementSetResponse{}, err
	}
	return response, nil
}

func (f ExperimentalFeatures) List(ctx context.Context, params protocolv2.ExperimentalFeatureListParams) (protocolv2.ExperimentalFeatureListResponse, error) {
	var response protocolv2.ExperimentalFeatureListResponse
	if err := f.client.callProtocol(ctx, protocolv2.MethodExperimentalFeatureList, params, &response); err != nil {
		return protocolv2.ExperimentalFeatureListResponse{}, err
	}
	return response, nil
}

func (f ExternalAgentConfigs) Detect(ctx context.Context, params protocolv2.ExternalAgentConfigDetectParams) (protocolv2.ExternalAgentConfigDetectResponse, error) {
	var response protocolv2.ExternalAgentConfigDetectResponse
	if err := f.client.callProtocol(ctx, protocolv2.MethodExternalAgentConfigDetect, params, &response); err != nil {
		return protocolv2.ExternalAgentConfigDetectResponse{}, err
	}
	return response, nil
}

func (f ExternalAgentConfigs) Import(ctx context.Context, params protocolv2.ExternalAgentConfigImportParams) (protocolv2.ExternalAgentConfigImportResponse, error) {
	var response protocolv2.ExternalAgentConfigImportResponse
	if err := f.client.callProtocol(ctx, protocolv2.MethodExternalAgentConfigImport, params, &response); err != nil {
		return protocolv2.ExternalAgentConfigImportResponse{}, err
	}
	return response, nil
}

func (f ExternalAgentConfigs) ImportReadHistories(ctx context.Context) (protocolv2.ExternalAgentConfigImportHistoriesReadResponse, error) {
	var response protocolv2.ExternalAgentConfigImportHistoriesReadResponse
	if err := f.client.callProtocolNoParams(ctx, protocolv2.MethodExternalAgentConfigImportReadHistories, &response); err != nil {
		return protocolv2.ExternalAgentConfigImportHistoriesReadResponse{}, err
	}
	return response, nil
}

func (f FS) Copy(ctx context.Context, params protocolv2.FsCopyParams) (protocolv2.FsCopyResponse, error) {
	var response protocolv2.FsCopyResponse
	if err := f.client.callProtocol(ctx, protocolv2.MethodFSCopy, params, &response); err != nil {
		return protocolv2.FsCopyResponse{}, err
	}
	return response, nil
}

func (f FS) CreateDirectory(ctx context.Context, params protocolv2.FsCreateDirectoryParams) (protocolv2.FsCreateDirectoryResponse, error) {
	var response protocolv2.FsCreateDirectoryResponse
	if err := f.client.callProtocol(ctx, protocolv2.MethodFSCreateDirectory, params, &response); err != nil {
		return protocolv2.FsCreateDirectoryResponse{}, err
	}
	return response, nil
}

func (f FS) GetMetadata(ctx context.Context, params protocolv2.FsGetMetadataParams) (protocolv2.FsGetMetadataResponse, error) {
	var response protocolv2.FsGetMetadataResponse
	if err := f.client.callProtocol(ctx, protocolv2.MethodFSGetMetadata, params, &response); err != nil {
		return protocolv2.FsGetMetadataResponse{}, err
	}
	return response, nil
}

func (f FS) ReadDirectory(ctx context.Context, params protocolv2.FsReadDirectoryParams) (protocolv2.FsReadDirectoryResponse, error) {
	var response protocolv2.FsReadDirectoryResponse
	if err := f.client.callProtocol(ctx, protocolv2.MethodFSReadDirectory, params, &response); err != nil {
		return protocolv2.FsReadDirectoryResponse{}, err
	}
	return response, nil
}

func (f FS) ReadFile(ctx context.Context, params protocolv2.FsReadFileParams) (protocolv2.FsReadFileResponse, error) {
	var response protocolv2.FsReadFileResponse
	if err := f.client.callProtocol(ctx, protocolv2.MethodFSReadFile, params, &response); err != nil {
		return protocolv2.FsReadFileResponse{}, err
	}
	return response, nil
}

func (f FS) Remove(ctx context.Context, params protocolv2.FsRemoveParams) (protocolv2.FsRemoveResponse, error) {
	var response protocolv2.FsRemoveResponse
	if err := f.client.callProtocol(ctx, protocolv2.MethodFSRemove, params, &response); err != nil {
		return protocolv2.FsRemoveResponse{}, err
	}
	return response, nil
}

func (f FS) Unwatch(ctx context.Context, params protocolv2.FsUnwatchParams) (protocolv2.FsUnwatchResponse, error) {
	var response protocolv2.FsUnwatchResponse
	if err := f.client.callProtocol(ctx, protocolv2.MethodFSUnwatch, params, &response); err != nil {
		return protocolv2.FsUnwatchResponse{}, err
	}
	return response, nil
}

func (f FS) Watch(ctx context.Context, params protocolv2.FsWatchParams) (protocolv2.FsWatchResponse, error) {
	var response protocolv2.FsWatchResponse
	if err := f.client.callProtocol(ctx, protocolv2.MethodFSWatch, params, &response); err != nil {
		return protocolv2.FsWatchResponse{}, err
	}
	return response, nil
}

func (f FS) WriteFile(ctx context.Context, params protocolv2.FsWriteFileParams) (protocolv2.FsWriteFileResponse, error) {
	var response protocolv2.FsWriteFileResponse
	if err := f.client.callProtocol(ctx, protocolv2.MethodFSWriteFile, params, &response); err != nil {
		return protocolv2.FsWriteFileResponse{}, err
	}
	return response, nil
}

func (f Feedback) Upload(ctx context.Context, params protocolv2.FeedbackUploadParams) (protocolv2.FeedbackUploadResponse, error) {
	var response protocolv2.FeedbackUploadResponse
	if err := f.client.callProtocol(ctx, protocolv2.MethodFeedbackUpload, params, &response); err != nil {
		return protocolv2.FeedbackUploadResponse{}, err
	}
	return response, nil
}

func (f FuzzyFileSearch) Search(ctx context.Context, params protocolv2.FuzzyFileSearchParams) (protocolv2.FuzzyFileSearchResponse, error) {
	var response protocolv2.FuzzyFileSearchResponse
	if err := f.client.callProtocol(ctx, protocolv2.MethodFuzzyFileSearch, params, &response); err != nil {
		return protocolv2.FuzzyFileSearchResponse{}, err
	}
	return response, nil
}

func (f FuzzyFileSearch) SessionStart(ctx context.Context, params protocolv2.FuzzyFileSearchSessionStartParams) (protocolv2.FuzzyFileSearchSessionStartResponse, error) {
	var response protocolv2.FuzzyFileSearchSessionStartResponse
	if err := f.client.callProtocol(ctx, protocolv2.MethodFuzzyFileSearchSessionStart, params, &response); err != nil {
		return protocolv2.FuzzyFileSearchSessionStartResponse{}, err
	}
	return response, nil
}

func (f FuzzyFileSearch) SessionStop(ctx context.Context, params protocolv2.FuzzyFileSearchSessionStopParams) (protocolv2.FuzzyFileSearchSessionStopResponse, error) {
	var response protocolv2.FuzzyFileSearchSessionStopResponse
	if err := f.client.callProtocol(ctx, protocolv2.MethodFuzzyFileSearchSessionStop, params, &response); err != nil {
		return protocolv2.FuzzyFileSearchSessionStopResponse{}, err
	}
	return response, nil
}

func (f FuzzyFileSearch) SessionUpdate(ctx context.Context, params protocolv2.FuzzyFileSearchSessionUpdateParams) (protocolv2.FuzzyFileSearchSessionUpdateResponse, error) {
	var response protocolv2.FuzzyFileSearchSessionUpdateResponse
	if err := f.client.callProtocol(ctx, protocolv2.MethodFuzzyFileSearchSessionUpdate, params, &response); err != nil {
		return protocolv2.FuzzyFileSearchSessionUpdateResponse{}, err
	}
	return response, nil
}

func (f Hooks) List(ctx context.Context, params protocolv2.HooksListParams) (protocolv2.HooksListResponse, error) {
	var response protocolv2.HooksListResponse
	if err := f.client.callProtocol(ctx, protocolv2.MethodHooksList, params, &response); err != nil {
		return protocolv2.HooksListResponse{}, err
	}
	return response, nil
}

func (f MCPServerStatus) List(ctx context.Context, params protocolv2.ListMcpServerStatusParams) (protocolv2.ListMcpServerStatusResponse, error) {
	var response protocolv2.ListMcpServerStatusResponse
	if err := f.client.callProtocol(ctx, protocolv2.MethodMCPServerStatusList, params, &response); err != nil {
		return protocolv2.ListMcpServerStatusResponse{}, err
	}
	return response, nil
}

func (f MCPServers) OAuthLogin(ctx context.Context, params protocolv2.McpServerOauthLoginParams) (protocolv2.McpServerOauthLoginResponse, error) {
	var response protocolv2.McpServerOauthLoginResponse
	if err := f.client.callProtocol(ctx, protocolv2.MethodMCPServerOAuthLogin, params, &response); err != nil {
		return protocolv2.McpServerOauthLoginResponse{}, err
	}
	return response, nil
}

func (f MCPServers) ResourceRead(ctx context.Context, params protocolv2.McpResourceReadParams) (protocolv2.McpResourceReadResponse, error) {
	var response protocolv2.McpResourceReadResponse
	if err := f.client.callProtocol(ctx, protocolv2.MethodMCPServerResourceRead, params, &response); err != nil {
		return protocolv2.McpResourceReadResponse{}, err
	}
	return response, nil
}

func (f MCPServers) ToolCall(ctx context.Context, params protocolv2.McpServerToolCallParams) (protocolv2.McpServerToolCallResponse, error) {
	var response protocolv2.McpServerToolCallResponse
	if err := f.client.callProtocol(ctx, protocolv2.MethodMCPServerToolCall, params, &response); err != nil {
		return protocolv2.McpServerToolCallResponse{}, err
	}
	return response, nil
}

func (f Marketplace) Add(ctx context.Context, params protocolv2.MarketplaceAddParams) (protocolv2.MarketplaceAddResponse, error) {
	var response protocolv2.MarketplaceAddResponse
	if err := f.client.callProtocol(ctx, protocolv2.MethodMarketplaceAdd, params, &response); err != nil {
		return protocolv2.MarketplaceAddResponse{}, err
	}
	return response, nil
}

func (f Marketplace) Remove(ctx context.Context, params protocolv2.MarketplaceRemoveParams) (protocolv2.MarketplaceRemoveResponse, error) {
	var response protocolv2.MarketplaceRemoveResponse
	if err := f.client.callProtocol(ctx, protocolv2.MethodMarketplaceRemove, params, &response); err != nil {
		return protocolv2.MarketplaceRemoveResponse{}, err
	}
	return response, nil
}

func (f Marketplace) Upgrade(ctx context.Context, params protocolv2.MarketplaceUpgradeParams) (protocolv2.MarketplaceUpgradeResponse, error) {
	var response protocolv2.MarketplaceUpgradeResponse
	if err := f.client.callProtocol(ctx, protocolv2.MethodMarketplaceUpgrade, params, &response); err != nil {
		return protocolv2.MarketplaceUpgradeResponse{}, err
	}
	return response, nil
}

func (f Memory) Reset(ctx context.Context) (protocolv2.MemoryResetResponse, error) {
	var response protocolv2.MemoryResetResponse
	if err := f.client.callProtocolNoParams(ctx, protocolv2.MethodMemoryReset, &response); err != nil {
		return protocolv2.MemoryResetResponse{}, err
	}
	return response, nil
}

func (f Mock) ExperimentalMethod(ctx context.Context, params protocolv2.MockExperimentalMethodParams) (protocolv2.MockExperimentalMethodResponse, error) {
	var response protocolv2.MockExperimentalMethodResponse
	if err := f.client.callProtocol(ctx, protocolv2.MethodMockExperimentalMethod, params, &response); err != nil {
		return protocolv2.MockExperimentalMethodResponse{}, err
	}
	return response, nil
}

func (f ModelProviders) CapabilitiesRead(ctx context.Context, params protocolv2.ModelProviderCapabilitiesReadParams) (protocolv2.ModelProviderCapabilitiesReadResponse, error) {
	var response protocolv2.ModelProviderCapabilitiesReadResponse
	if err := f.client.callProtocol(ctx, protocolv2.MethodModelProviderCapabilitiesRead, params, &response); err != nil {
		return protocolv2.ModelProviderCapabilitiesReadResponse{}, err
	}
	return response, nil
}

func (f Models) List(ctx context.Context, params protocolv2.ModelListParams) (protocolv2.ModelListResponse, error) {
	var response protocolv2.ModelListResponse
	if err := f.client.callProtocol(ctx, protocolv2.MethodModelList, params, &response); err != nil {
		return protocolv2.ModelListResponse{}, err
	}
	return response, nil
}

func (f Plugins) Install(ctx context.Context, params protocolv2.PluginInstallParams) (protocolv2.PluginInstallResponse, error) {
	var response protocolv2.PluginInstallResponse
	if err := f.client.callProtocol(ctx, protocolv2.MethodPluginInstall, params, &response); err != nil {
		return protocolv2.PluginInstallResponse{}, err
	}
	return response, nil
}

func (f Plugins) Installed(ctx context.Context, params protocolv2.PluginInstalledParams) (protocolv2.PluginInstalledResponse, error) {
	var response protocolv2.PluginInstalledResponse
	if err := f.client.callProtocol(ctx, protocolv2.MethodPluginInstalled, params, &response); err != nil {
		return protocolv2.PluginInstalledResponse{}, err
	}
	return response, nil
}

func (f Plugins) List(ctx context.Context, params protocolv2.PluginListParams) (protocolv2.PluginListResponse, error) {
	var response protocolv2.PluginListResponse
	if err := f.client.callProtocol(ctx, protocolv2.MethodPluginList, params, &response); err != nil {
		return protocolv2.PluginListResponse{}, err
	}
	return response, nil
}

func (f Plugins) Read(ctx context.Context, params protocolv2.PluginReadParams) (protocolv2.PluginReadResponse, error) {
	var response protocolv2.PluginReadResponse
	if err := f.client.callProtocol(ctx, protocolv2.MethodPluginRead, params, &response); err != nil {
		return protocolv2.PluginReadResponse{}, err
	}
	return response, nil
}

func (f Plugins) ShareCheckout(ctx context.Context, params protocolv2.PluginShareCheckoutParams) (protocolv2.PluginShareCheckoutResponse, error) {
	var response protocolv2.PluginShareCheckoutResponse
	if err := f.client.callProtocol(ctx, protocolv2.MethodPluginShareCheckout, params, &response); err != nil {
		return protocolv2.PluginShareCheckoutResponse{}, err
	}
	return response, nil
}

func (f Plugins) ShareDelete(ctx context.Context, params protocolv2.PluginShareDeleteParams) (protocolv2.PluginShareDeleteResponse, error) {
	var response protocolv2.PluginShareDeleteResponse
	if err := f.client.callProtocol(ctx, protocolv2.MethodPluginShareDelete, params, &response); err != nil {
		return protocolv2.PluginShareDeleteResponse{}, err
	}
	return response, nil
}

func (f Plugins) ShareList(ctx context.Context, params protocolv2.PluginShareListParams) (protocolv2.PluginShareListResponse, error) {
	var response protocolv2.PluginShareListResponse
	if err := f.client.callProtocol(ctx, protocolv2.MethodPluginShareList, params, &response); err != nil {
		return protocolv2.PluginShareListResponse{}, err
	}
	return response, nil
}

func (f Plugins) ShareSave(ctx context.Context, params protocolv2.PluginShareSaveParams) (protocolv2.PluginShareSaveResponse, error) {
	var response protocolv2.PluginShareSaveResponse
	if err := f.client.callProtocol(ctx, protocolv2.MethodPluginShareSave, params, &response); err != nil {
		return protocolv2.PluginShareSaveResponse{}, err
	}
	return response, nil
}

func (f Plugins) ShareUpdateTargets(ctx context.Context, params protocolv2.PluginShareUpdateTargetsParams) (protocolv2.PluginShareUpdateTargetsResponse, error) {
	var response protocolv2.PluginShareUpdateTargetsResponse
	if err := f.client.callProtocol(ctx, protocolv2.MethodPluginShareUpdateTargets, params, &response); err != nil {
		return protocolv2.PluginShareUpdateTargetsResponse{}, err
	}
	return response, nil
}

func (f Plugins) SkillRead(ctx context.Context, params protocolv2.PluginSkillReadParams) (protocolv2.PluginSkillReadResponse, error) {
	var response protocolv2.PluginSkillReadResponse
	if err := f.client.callProtocol(ctx, protocolv2.MethodPluginSkillRead, params, &response); err != nil {
		return protocolv2.PluginSkillReadResponse{}, err
	}
	return response, nil
}

func (f Plugins) Uninstall(ctx context.Context, params protocolv2.PluginUninstallParams) (protocolv2.PluginUninstallResponse, error) {
	var response protocolv2.PluginUninstallResponse
	if err := f.client.callProtocol(ctx, protocolv2.MethodPluginUninstall, params, &response); err != nil {
		return protocolv2.PluginUninstallResponse{}, err
	}
	return response, nil
}

func (f Processes) Kill(ctx context.Context, params protocolv2.ProcessKillParams) (protocolv2.ProcessKillResponse, error) {
	var response protocolv2.ProcessKillResponse
	if err := f.client.callProtocol(ctx, protocolv2.MethodProcessKill, params, &response); err != nil {
		return protocolv2.ProcessKillResponse{}, err
	}
	return response, nil
}

func (f Processes) ResizePTY(ctx context.Context, params protocolv2.ProcessResizePtyParams) (protocolv2.ProcessResizePtyResponse, error) {
	var response protocolv2.ProcessResizePtyResponse
	if err := f.client.callProtocol(ctx, protocolv2.MethodProcessResizePTY, params, &response); err != nil {
		return protocolv2.ProcessResizePtyResponse{}, err
	}
	return response, nil
}

func (f Processes) Spawn(ctx context.Context, params protocolv2.ProcessSpawnParams) (protocolv2.ProcessSpawnResponse, error) {
	var response protocolv2.ProcessSpawnResponse
	if err := f.client.callProtocol(ctx, protocolv2.MethodProcessSpawn, params, &response); err != nil {
		return protocolv2.ProcessSpawnResponse{}, err
	}
	return response, nil
}

func (f Processes) WriteStdin(ctx context.Context, params protocolv2.ProcessWriteStdinParams) (protocolv2.ProcessWriteStdinResponse, error) {
	var response protocolv2.ProcessWriteStdinResponse
	if err := f.client.callProtocol(ctx, protocolv2.MethodProcessWriteStdin, params, &response); err != nil {
		return protocolv2.ProcessWriteStdinResponse{}, err
	}
	return response, nil
}

func (f RemoteControl) ClientRevoke(ctx context.Context, params protocolv2.RemoteControlClientsRevokeParams) (protocolv2.RemoteControlClientsRevokeResponse, error) {
	var response protocolv2.RemoteControlClientsRevokeResponse
	if err := f.client.callProtocol(ctx, protocolv2.MethodRemoteControlClientRevoke, params, &response); err != nil {
		return protocolv2.RemoteControlClientsRevokeResponse{}, err
	}
	return response, nil
}

func (f RemoteControl) Disable(ctx context.Context) (protocolv2.RemoteControlDisableResponse, error) {
	var response protocolv2.RemoteControlDisableResponse
	if err := f.client.callProtocolNoParams(ctx, protocolv2.MethodRemoteControlDisable, &response); err != nil {
		return protocolv2.RemoteControlDisableResponse{}, err
	}
	return response, nil
}

func (f RemoteControl) Enable(ctx context.Context) (protocolv2.RemoteControlEnableResponse, error) {
	var response protocolv2.RemoteControlEnableResponse
	if err := f.client.callProtocolNoParams(ctx, protocolv2.MethodRemoteControlEnable, &response); err != nil {
		return protocolv2.RemoteControlEnableResponse{}, err
	}
	return response, nil
}

func (f RemoteControl) PairingStart(ctx context.Context, params protocolv2.RemoteControlPairingStartParams) (protocolv2.RemoteControlPairingStartResponse, error) {
	var response protocolv2.RemoteControlPairingStartResponse
	if err := f.client.callProtocol(ctx, protocolv2.MethodRemoteControlPairingStart, params, &response); err != nil {
		return protocolv2.RemoteControlPairingStartResponse{}, err
	}
	return response, nil
}

func (f RemoteControl) PairingStatus(ctx context.Context, params protocolv2.RemoteControlPairingStatusParams) (protocolv2.RemoteControlPairingStatusResponse, error) {
	var response protocolv2.RemoteControlPairingStatusResponse
	if err := f.client.callProtocol(ctx, protocolv2.MethodRemoteControlPairingStatus, params, &response); err != nil {
		return protocolv2.RemoteControlPairingStatusResponse{}, err
	}
	return response, nil
}

func (f RemoteControl) StatusRead(ctx context.Context) (protocolv2.RemoteControlStatusReadResponse, error) {
	var response protocolv2.RemoteControlStatusReadResponse
	if err := f.client.callProtocolNoParams(ctx, protocolv2.MethodRemoteControlStatusRead, &response); err != nil {
		return protocolv2.RemoteControlStatusReadResponse{}, err
	}
	return response, nil
}

func (f Reviews) Start(ctx context.Context, params protocolv2.ReviewStartParams) (protocolv2.ReviewStartResponse, error) {
	var response protocolv2.ReviewStartResponse
	if err := f.client.callProtocol(ctx, protocolv2.MethodReviewStart, params, &response); err != nil {
		return protocolv2.ReviewStartResponse{}, err
	}
	return response, nil
}

func (f Skills) ConfigWrite(ctx context.Context, params protocolv2.SkillsConfigWriteParams) (protocolv2.SkillsConfigWriteResponse, error) {
	var response protocolv2.SkillsConfigWriteResponse
	if err := f.client.callProtocol(ctx, protocolv2.MethodSkillsConfigWrite, params, &response); err != nil {
		return protocolv2.SkillsConfigWriteResponse{}, err
	}
	return response, nil
}

func (f Skills) ExtraRootsSet(ctx context.Context, params protocolv2.SkillsExtraRootsSetParams) (protocolv2.SkillsExtraRootsSetResponse, error) {
	var response protocolv2.SkillsExtraRootsSetResponse
	if err := f.client.callProtocol(ctx, protocolv2.MethodSkillsExtraRootsSet, params, &response); err != nil {
		return protocolv2.SkillsExtraRootsSetResponse{}, err
	}
	return response, nil
}

func (f Skills) List(ctx context.Context, params protocolv2.SkillsListParams) (protocolv2.SkillsListResponse, error) {
	var response protocolv2.SkillsListResponse
	if err := f.client.callProtocol(ctx, protocolv2.MethodSkillsList, params, &response); err != nil {
		return protocolv2.SkillsListResponse{}, err
	}
	return response, nil
}

func (f Threads) ApproveGuardianDeniedAction(ctx context.Context, params protocolv2.ThreadApproveGuardianDeniedActionParams) (protocolv2.ThreadApproveGuardianDeniedActionResponse, error) {
	var response protocolv2.ThreadApproveGuardianDeniedActionResponse
	if err := f.client.callProtocol(ctx, protocolv2.MethodThreadApproveGuardianDeniedAction, params, &response); err != nil {
		return protocolv2.ThreadApproveGuardianDeniedActionResponse{}, err
	}
	return response, nil
}

func (f Threads) Archive(ctx context.Context, params protocolv2.ThreadArchiveParams) (protocolv2.ThreadArchiveResponse, error) {
	var response protocolv2.ThreadArchiveResponse
	if err := f.client.callProtocol(ctx, protocolv2.MethodThreadArchive, params, &response); err != nil {
		return protocolv2.ThreadArchiveResponse{}, err
	}
	return response, nil
}

func (f Threads) BackgroundTerminalsClean(ctx context.Context, params protocolv2.ThreadBackgroundTerminalsCleanParams) (protocolv2.ThreadBackgroundTerminalsCleanResponse, error) {
	var response protocolv2.ThreadBackgroundTerminalsCleanResponse
	if err := f.client.callProtocol(ctx, protocolv2.MethodThreadBackgroundTerminalsClean, params, &response); err != nil {
		return protocolv2.ThreadBackgroundTerminalsCleanResponse{}, err
	}
	return response, nil
}

func (f Threads) BackgroundTerminalsTerminate(ctx context.Context, params protocolv2.ThreadBackgroundTerminalsTerminateParams) (protocolv2.ThreadBackgroundTerminalsTerminateResponse, error) {
	var response protocolv2.ThreadBackgroundTerminalsTerminateResponse
	if err := f.client.callProtocol(ctx, protocolv2.MethodThreadBackgroundTerminalsTerminate, params, &response); err != nil {
		return protocolv2.ThreadBackgroundTerminalsTerminateResponse{}, err
	}
	return response, nil
}

func (f Threads) CompactStart(ctx context.Context, params protocolv2.ThreadCompactStartParams) (protocolv2.ThreadCompactStartResponse, error) {
	var response protocolv2.ThreadCompactStartResponse
	if err := f.client.callProtocol(ctx, protocolv2.MethodThreadCompactStart, params, &response); err != nil {
		return protocolv2.ThreadCompactStartResponse{}, err
	}
	return response, nil
}

func (f Threads) DecrementElicitation(ctx context.Context, params protocolv2.ThreadDecrementElicitationParams) (protocolv2.ThreadDecrementElicitationResponse, error) {
	var response protocolv2.ThreadDecrementElicitationResponse
	if err := f.client.callProtocol(ctx, protocolv2.MethodThreadDecrementElicitation, params, &response); err != nil {
		return protocolv2.ThreadDecrementElicitationResponse{}, err
	}
	return response, nil
}

func (f Threads) Delete(ctx context.Context, params protocolv2.ThreadDeleteParams) (protocolv2.ThreadDeleteResponse, error) {
	var response protocolv2.ThreadDeleteResponse
	if err := f.client.callProtocol(ctx, protocolv2.MethodThreadDelete, params, &response); err != nil {
		return protocolv2.ThreadDeleteResponse{}, err
	}
	return response, nil
}

func (f Threads) Fork(ctx context.Context, params protocolv2.ThreadForkParams) (protocolv2.ThreadForkResponse, error) {
	var response protocolv2.ThreadForkResponse
	if err := f.client.callProtocol(ctx, protocolv2.MethodThreadFork, params, &response); err != nil {
		return protocolv2.ThreadForkResponse{}, err
	}
	return response, nil
}

func (f Threads) GoalClear(ctx context.Context, params protocolv2.ThreadGoalClearParams) (protocolv2.ThreadGoalClearResponse, error) {
	var response protocolv2.ThreadGoalClearResponse
	if err := f.client.callProtocol(ctx, protocolv2.MethodThreadGoalClear, params, &response); err != nil {
		return protocolv2.ThreadGoalClearResponse{}, err
	}
	return response, nil
}

func (f Threads) GoalGet(ctx context.Context, params protocolv2.ThreadGoalGetParams) (protocolv2.ThreadGoalGetResponse, error) {
	var response protocolv2.ThreadGoalGetResponse
	if err := f.client.callProtocol(ctx, protocolv2.MethodThreadGoalGet, params, &response); err != nil {
		return protocolv2.ThreadGoalGetResponse{}, err
	}
	return response, nil
}

func (f Threads) GoalSet(ctx context.Context, params protocolv2.ThreadGoalSetParams) (protocolv2.ThreadGoalSetResponse, error) {
	var response protocolv2.ThreadGoalSetResponse
	if err := f.client.callProtocol(ctx, protocolv2.MethodThreadGoalSet, params, &response); err != nil {
		return protocolv2.ThreadGoalSetResponse{}, err
	}
	return response, nil
}

func (f Threads) IncrementElicitation(ctx context.Context, params protocolv2.ThreadIncrementElicitationParams) (protocolv2.ThreadIncrementElicitationResponse, error) {
	var response protocolv2.ThreadIncrementElicitationResponse
	if err := f.client.callProtocol(ctx, protocolv2.MethodThreadIncrementElicitation, params, &response); err != nil {
		return protocolv2.ThreadIncrementElicitationResponse{}, err
	}
	return response, nil
}

func (f Threads) InjectItems(ctx context.Context, params protocolv2.ThreadInjectItemsParams) (protocolv2.ThreadInjectItemsResponse, error) {
	var response protocolv2.ThreadInjectItemsResponse
	if err := f.client.callProtocol(ctx, protocolv2.MethodThreadInjectItems, params, &response); err != nil {
		return protocolv2.ThreadInjectItemsResponse{}, err
	}
	return response, nil
}

func (f Threads) ItemsList(ctx context.Context, params protocolv2.ThreadItemsListParams) (protocolv2.ThreadItemsListResponse, error) {
	var response protocolv2.ThreadItemsListResponse
	if err := f.client.callProtocol(ctx, protocolv2.MethodThreadItemsList, params, &response); err != nil {
		return protocolv2.ThreadItemsListResponse{}, err
	}
	return response, nil
}

func (f Threads) List(ctx context.Context, params protocolv2.ThreadListParams) (protocolv2.ThreadListResponse, error) {
	var response protocolv2.ThreadListResponse
	if err := f.client.callProtocol(ctx, protocolv2.MethodThreadList, params, &response); err != nil {
		return protocolv2.ThreadListResponse{}, err
	}
	return response, nil
}

func (f Threads) LoadedList(ctx context.Context, params protocolv2.ThreadLoadedListParams) (protocolv2.ThreadLoadedListResponse, error) {
	var response protocolv2.ThreadLoadedListResponse
	if err := f.client.callProtocol(ctx, protocolv2.MethodThreadLoadedList, params, &response); err != nil {
		return protocolv2.ThreadLoadedListResponse{}, err
	}
	return response, nil
}

func (f Threads) MemoryModeSet(ctx context.Context, params protocolv2.ThreadMemoryModeSetParams) (protocolv2.ThreadMemoryModeSetResponse, error) {
	var response protocolv2.ThreadMemoryModeSetResponse
	if err := f.client.callProtocol(ctx, protocolv2.MethodThreadMemoryModeSet, params, &response); err != nil {
		return protocolv2.ThreadMemoryModeSetResponse{}, err
	}
	return response, nil
}

func (f Threads) MetadataUpdate(ctx context.Context, params protocolv2.ThreadMetadataUpdateParams) (protocolv2.ThreadMetadataUpdateResponse, error) {
	var response protocolv2.ThreadMetadataUpdateResponse
	if err := f.client.callProtocol(ctx, protocolv2.MethodThreadMetadataUpdate, params, &response); err != nil {
		return protocolv2.ThreadMetadataUpdateResponse{}, err
	}
	return response, nil
}

func (f Threads) NameSet(ctx context.Context, params protocolv2.ThreadSetNameParams) (protocolv2.ThreadSetNameResponse, error) {
	var response protocolv2.ThreadSetNameResponse
	if err := f.client.callProtocol(ctx, protocolv2.MethodThreadNameSet, params, &response); err != nil {
		return protocolv2.ThreadSetNameResponse{}, err
	}
	return response, nil
}

func (f Threads) Read(ctx context.Context, params protocolv2.ThreadReadParams) (protocolv2.ThreadReadResponse, error) {
	var response protocolv2.ThreadReadResponse
	if err := f.client.callProtocol(ctx, protocolv2.MethodThreadRead, params, &response); err != nil {
		return protocolv2.ThreadReadResponse{}, err
	}
	return response, nil
}

func (f Threads) RealtimeAppendAudio(ctx context.Context, params protocolv2.ThreadRealtimeAppendAudioParams) (protocolv2.ThreadRealtimeAppendAudioResponse, error) {
	var response protocolv2.ThreadRealtimeAppendAudioResponse
	if err := f.client.callProtocol(ctx, protocolv2.MethodThreadRealtimeAppendAudio, params, &response); err != nil {
		return protocolv2.ThreadRealtimeAppendAudioResponse{}, err
	}
	return response, nil
}

func (f Threads) RealtimeAppendSpeech(ctx context.Context, params protocolv2.ThreadRealtimeAppendSpeechParams) (protocolv2.ThreadRealtimeAppendSpeechResponse, error) {
	var response protocolv2.ThreadRealtimeAppendSpeechResponse
	if err := f.client.callProtocol(ctx, protocolv2.MethodThreadRealtimeAppendSpeech, params, &response); err != nil {
		return protocolv2.ThreadRealtimeAppendSpeechResponse{}, err
	}
	return response, nil
}

func (f Threads) RealtimeAppendText(ctx context.Context, params protocolv2.ThreadRealtimeAppendTextParams) (protocolv2.ThreadRealtimeAppendTextResponse, error) {
	var response protocolv2.ThreadRealtimeAppendTextResponse
	if err := f.client.callProtocol(ctx, protocolv2.MethodThreadRealtimeAppendText, params, &response); err != nil {
		return protocolv2.ThreadRealtimeAppendTextResponse{}, err
	}
	return response, nil
}

func (f Threads) RealtimeListVoices(ctx context.Context, params protocolv2.ThreadRealtimeListVoicesParams) (protocolv2.ThreadRealtimeListVoicesResponse, error) {
	var response protocolv2.ThreadRealtimeListVoicesResponse
	if err := f.client.callProtocol(ctx, protocolv2.MethodThreadRealtimeListVoices, params, &response); err != nil {
		return protocolv2.ThreadRealtimeListVoicesResponse{}, err
	}
	return response, nil
}

func (f Threads) RealtimeStart(ctx context.Context, params protocolv2.ThreadRealtimeStartParams) (protocolv2.ThreadRealtimeStartResponse, error) {
	var response protocolv2.ThreadRealtimeStartResponse
	if err := f.client.callProtocol(ctx, protocolv2.MethodThreadRealtimeStart, params, &response); err != nil {
		return protocolv2.ThreadRealtimeStartResponse{}, err
	}
	return response, nil
}

func (f Threads) RealtimeStop(ctx context.Context, params protocolv2.ThreadRealtimeStopParams) (protocolv2.ThreadRealtimeStopResponse, error) {
	var response protocolv2.ThreadRealtimeStopResponse
	if err := f.client.callProtocol(ctx, protocolv2.MethodThreadRealtimeStop, params, &response); err != nil {
		return protocolv2.ThreadRealtimeStopResponse{}, err
	}
	return response, nil
}

func (f Threads) Resume(ctx context.Context, params protocolv2.ThreadResumeParams) (protocolv2.ThreadResumeResponse, error) {
	var response protocolv2.ThreadResumeResponse
	if err := f.client.callProtocol(ctx, protocolv2.MethodThreadResume, params, &response); err != nil {
		return protocolv2.ThreadResumeResponse{}, err
	}
	return response, nil
}

func (f Threads) Rollback(ctx context.Context, params protocolv2.ThreadRollbackParams) (protocolv2.ThreadRollbackResponse, error) {
	var response protocolv2.ThreadRollbackResponse
	if err := f.client.callProtocol(ctx, protocolv2.MethodThreadRollback, params, &response); err != nil {
		return protocolv2.ThreadRollbackResponse{}, err
	}
	return response, nil
}

func (f Threads) SettingsUpdate(ctx context.Context, params protocolv2.ThreadSettingsUpdateParams) (protocolv2.ThreadSettingsUpdateResponse, error) {
	var response protocolv2.ThreadSettingsUpdateResponse
	if err := f.client.callProtocol(ctx, protocolv2.MethodThreadSettingsUpdate, params, &response); err != nil {
		return protocolv2.ThreadSettingsUpdateResponse{}, err
	}
	return response, nil
}

func (f Threads) ShellCommand(ctx context.Context, params protocolv2.ThreadShellCommandParams) (protocolv2.ThreadShellCommandResponse, error) {
	var response protocolv2.ThreadShellCommandResponse
	if err := f.client.callProtocol(ctx, protocolv2.MethodThreadShellCommand, params, &response); err != nil {
		return protocolv2.ThreadShellCommandResponse{}, err
	}
	return response, nil
}

func (f Threads) Start(ctx context.Context, params protocolv2.ThreadStartParams) (protocolv2.ThreadStartResponse, error) {
	var response protocolv2.ThreadStartResponse
	if err := f.client.callProtocol(ctx, protocolv2.MethodThreadStart, params, &response); err != nil {
		return protocolv2.ThreadStartResponse{}, err
	}
	return response, nil
}

func (f Threads) TurnsList(ctx context.Context, params protocolv2.ThreadTurnsListParams) (protocolv2.ThreadTurnsListResponse, error) {
	var response protocolv2.ThreadTurnsListResponse
	if err := f.client.callProtocol(ctx, protocolv2.MethodThreadTurnsList, params, &response); err != nil {
		return protocolv2.ThreadTurnsListResponse{}, err
	}
	return response, nil
}

func (f Threads) Unarchive(ctx context.Context, params protocolv2.ThreadUnarchiveParams) (protocolv2.ThreadUnarchiveResponse, error) {
	var response protocolv2.ThreadUnarchiveResponse
	if err := f.client.callProtocol(ctx, protocolv2.MethodThreadUnarchive, params, &response); err != nil {
		return protocolv2.ThreadUnarchiveResponse{}, err
	}
	return response, nil
}

func (f Threads) Unsubscribe(ctx context.Context, params protocolv2.ThreadUnsubscribeParams) (protocolv2.ThreadUnsubscribeResponse, error) {
	var response protocolv2.ThreadUnsubscribeResponse
	if err := f.client.callProtocol(ctx, protocolv2.MethodThreadUnsubscribe, params, &response); err != nil {
		return protocolv2.ThreadUnsubscribeResponse{}, err
	}
	return response, nil
}

func (f Turns) Interrupt(ctx context.Context, params protocolv2.TurnInterruptParams) (protocolv2.TurnInterruptResponse, error) {
	var response protocolv2.TurnInterruptResponse
	if err := f.client.callProtocol(ctx, protocolv2.MethodTurnInterrupt, params, &response); err != nil {
		return protocolv2.TurnInterruptResponse{}, err
	}
	return response, nil
}

func (f Turns) Start(ctx context.Context, params protocolv2.TurnStartParams) (protocolv2.TurnStartResponse, error) {
	var response protocolv2.TurnStartResponse
	if err := f.client.callProtocol(ctx, protocolv2.MethodTurnStart, params, &response); err != nil {
		return protocolv2.TurnStartResponse{}, err
	}
	return response, nil
}

func (f Turns) Steer(ctx context.Context, params protocolv2.TurnSteerParams) (protocolv2.TurnSteerResponse, error) {
	var response protocolv2.TurnSteerResponse
	if err := f.client.callProtocol(ctx, protocolv2.MethodTurnSteer, params, &response); err != nil {
		return protocolv2.TurnSteerResponse{}, err
	}
	return response, nil
}

func (f WindowsSandbox) Readiness(ctx context.Context) (protocolv2.WindowsSandboxReadinessResponse, error) {
	var response protocolv2.WindowsSandboxReadinessResponse
	if err := f.client.callProtocolNoParams(ctx, protocolv2.MethodWindowsSandboxReadiness, &response); err != nil {
		return protocolv2.WindowsSandboxReadinessResponse{}, err
	}
	return response, nil
}

func (f WindowsSandbox) SetupStart(ctx context.Context, params protocolv2.WindowsSandboxSetupStartParams) (protocolv2.WindowsSandboxSetupStartResponse, error) {
	var response protocolv2.WindowsSandboxSetupStartResponse
	if err := f.client.callProtocol(ctx, protocolv2.MethodWindowsSandboxSetupStart, params, &response); err != nil {
		return protocolv2.WindowsSandboxSetupStartResponse{}, err
	}
	return response, nil
}
