package generatedproof

import (
	"fmt"
	"go/format"
	"regexp"
	"sort"
	"strings"

	"github.com/ronhuafeng/llm-go/codexsdk/internal/protocolgen"
)

const (
	facadeStatusGenerated = "generated"
	facadeStatusDeferred  = "deferred_missing_generated_types"
)

var (
	facadeTargetRE = regexp.MustCompile(`^([A-Za-z][A-Za-z0-9]*)\(\)\.([A-Za-z][A-Za-z0-9]*)$`)
	methodConstRE  = regexp.MustCompile(`(?m)^\s*(Method[A-Za-z0-9]+)\s+=\s+"([^"]+)"`)
	typeDeclRE     = regexp.MustCompile(`(?m)^type\s+([A-Za-z][A-Za-z0-9]*)\b`)
)

type surfaceMethod struct {
	accessor     string
	operation    string
	method       string
	methodConst  string
	paramsType   string
	responseType string
}

// GenerateSDKSurface renders the public generated facade from classified manifest facts.
func GenerateSDKSurface(manifest protocolgen.Manifest, methodRegistry, protocolTypes []byte) ([]byte, error) {
	methodConsts := map[string]string{}
	for _, match := range methodConstRE.FindAllSubmatch(methodRegistry, -1) {
		methodConsts[string(match[2])] = string(match[1])
	}
	typeNames := map[string]bool{}
	for _, match := range typeDeclRE.FindAllSubmatch(protocolTypes, -1) {
		typeNames[string(match[1])] = true
	}

	var methods []surfaceMethod
	seen := map[string]bool{}
	for _, entry := range manifest.Entries {
		if entry.Direction != "client_to_server" || entry.Kind != "request" {
			continue
		}
		if strings.HasPrefix(entry.FacadeTarget, "internal.") {
			continue
		}
		match := facadeTargetRE.FindStringSubmatch(entry.FacadeTarget)
		if match == nil {
			return nil, fmt.Errorf("invalid generated facade target %q for method %q", entry.FacadeTarget, entry.Method)
		}
		accessor, operation := match[1], match[2]
		methodConst := methodConsts[entry.Method]
		var missing []string
		if methodConst == "" {
			missing = append(missing, "method constant")
		}
		if entry.ParamsOrPayloadSchema != "" && !typeNames[entry.ParamsOrPayloadSchema] {
			missing = append(missing, "params type "+entry.ParamsOrPayloadSchema)
		}
		if entry.ResponseType == "" || !typeNames[entry.ResponseType] {
			if entry.ResponseType == "" {
				missing = append(missing, "response type <empty>")
			} else {
				missing = append(missing, "response type "+entry.ResponseType)
			}
		}
		switch entry.FacadeStatus {
		case facadeStatusDeferred:
			if len(missing) == 0 {
				return nil, fmt.Errorf("deferred facade method %q has all generated prerequisites; mark it generated", entry.Method)
			}
			continue
		case facadeStatusGenerated:
			if len(missing) > 0 {
				return nil, fmt.Errorf("generated facade method %q is missing %s", entry.Method, strings.Join(missing, ", "))
			}
		default:
			return nil, fmt.Errorf("facade method %q has invalid or missing facade_status %q", entry.Method, entry.FacadeStatus)
		}
		key := accessor + "\x00" + operation
		if seen[key] {
			return nil, fmt.Errorf("duplicate facade operation %s().%s", accessor, operation)
		}
		seen[key] = true
		methods = append(methods, surfaceMethod{
			accessor:     accessor,
			operation:    operation,
			method:       entry.Method,
			methodConst:  methodConst,
			paramsType:   entry.ParamsOrPayloadSchema,
			responseType: entry.ResponseType,
		})
	}
	sort.Slice(methods, func(i, j int) bool {
		if methods[i].accessor != methods[j].accessor {
			return methods[i].accessor < methods[j].accessor
		}
		if methods[i].operation != methods[j].operation {
			return methods[i].operation < methods[j].operation
		}
		return methods[i].method < methods[j].method
	})

	var b strings.Builder
	b.WriteString("// Code generated by scripts/codexsdk_generate_sdk_surface.py; DO NOT EDIT.\n\n")
	b.WriteString("package codexsdk\n\n")
	b.WriteString("import (\n")
	b.WriteString("\t\"context\"\n\n")
	b.WriteString("\t\"github.com/ronhuafeng/llm-go/codexsdk/protocolv2\"\n")
	b.WriteString(")\n\n")

	byAccessor := map[string][]surfaceMethod{}
	var accessors []string
	for _, method := range methods {
		if _, ok := byAccessor[method.accessor]; !ok {
			accessors = append(accessors, method.accessor)
		}
		byAccessor[method.accessor] = append(byAccessor[method.accessor], method)
	}
	sort.Strings(accessors)
	for _, accessor := range accessors {
		b.WriteString("// " + accessor + " is an opaque generated facade for exact Codex operations.\n")
		b.WriteString("type " + accessor + " struct {\n")
		b.WriteString("\tclient *Client\n")
		b.WriteString("}\n\n")
		b.WriteString("func (c *Client) " + accessor + "() " + accessor + " {\n")
		b.WriteString("\treturn " + accessor + "{client: c}\n")
		b.WriteString("}\n\n")
	}
	for _, method := range methods {
		if method.paramsType != "" {
			fmt.Fprintf(&b, "func (f %s) %s(ctx context.Context, params protocolv2.%s) (protocolv2.%s, error) {\n", method.accessor, method.operation, method.paramsType, method.responseType)
			fmt.Fprintf(&b, "\tvar response protocolv2.%s\n", method.responseType)
			fmt.Fprintf(&b, "\tif err := f.client.callProtocol(ctx, protocolv2.%s, params, &response); err != nil {\n", method.methodConst)
			fmt.Fprintf(&b, "\t\treturn protocolv2.%s{}, err\n", method.responseType)
			b.WriteString("\t}\n")
			b.WriteString("\treturn response, nil\n")
			b.WriteString("}\n\n")
			continue
		}
		fmt.Fprintf(&b, "func (f %s) %s(ctx context.Context) (protocolv2.%s, error) {\n", method.accessor, method.operation, method.responseType)
		fmt.Fprintf(&b, "\tvar response protocolv2.%s\n", method.responseType)
		fmt.Fprintf(&b, "\tif err := f.client.callProtocolNoParams(ctx, protocolv2.%s, &response); err != nil {\n", method.methodConst)
		fmt.Fprintf(&b, "\t\treturn protocolv2.%s{}, err\n", method.responseType)
		b.WriteString("\t}\n")
		b.WriteString("\treturn response, nil\n")
		b.WriteString("}\n\n")
	}

	formatted, err := format.Source([]byte(b.String()))
	if err != nil {
		return nil, fmt.Errorf("format generated sdk surface: %w", err)
	}
	return formatted, nil
}
