package protocolgen

import (
	"bytes"
	"fmt"
	"go/format"
	"regexp"
	"sort"
	"strings"
	"unicode"
	"unicode/utf8"
)

var jsonTagPattern = regexp.MustCompile(`json:"([^,"]+)`)

type experimentalMemberIndex struct {
	fields      map[string]map[string]struct{}
	unionValues map[string]map[string]struct{}
	childTypes  map[string]map[string]string
}

func GenerateExperimentalMembers(manifest Manifest) ([]byte, error) {
	index := experimentalMemberIndex{
		fields:      map[string]map[string]struct{}{},
		unionValues: map[string]map[string]struct{}{},
		childTypes:  map[string]map[string]string{},
	}
	for _, entry := range manifest.Surface {
		switch entry.Kind {
		case SurfaceField:
			owner := entry.Owner
			if owner == "" {
				owner, _, _ = strings.Cut(entry.Name, ".")
			}
			if owner == "" {
				continue
			}
			jsonName, ok := jsonFieldName(entry.Signature)
			if !ok || jsonName == "-" {
				continue
			}
			if child, ok := namedProtocolChildType(entry.Signature); ok {
				setNestedMap(index.childTypes, owner, jsonName, child)
			}
			if entry.Stability == StabilityExperimental {
				setNestedSet(index.fields, owner, jsonName)
			}
		case SurfaceValue, SurfaceConst:
			if entry.Stability != StabilityExperimental {
				continue
			}
			owner, value, ok := experimentalUnionValue(entry)
			if !ok {
				continue
			}
			setNestedSet(index.unionValues, owner, value)
		}
	}
	var out bytes.Buffer
	out.WriteString("// Code generated by protocolv2gen; DO NOT EDIT.\n")
	out.WriteString("package protocolv2\n\n")
	writeStringSetMap(&out, "ExperimentalJSONFields", index.fields)
	out.WriteString("\n")
	writeStringSetMap(&out, "ExperimentalUnionValues", index.unionValues)
	out.WriteString("\n")
	writeStringStringMap(&out, "ExperimentalChildTypes", index.childTypes)
	formatted, err := format.Source(out.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format generated experimental members: %w", err)
	}
	return formatted, nil
}

func jsonFieldName(signature string) (string, bool) {
	match := jsonTagPattern.FindStringSubmatch(signature)
	if len(match) != 2 {
		return "", false
	}
	return match[1], true
}

func experimentalUnionValue(entry SurfaceEntry) (owner, value string, ok bool) {
	owner = strings.TrimSuffix(entry.Owner, "Kind")
	if owner == "" || owner == entry.Owner {
		if idx := strings.Index(entry.Name, "Kind"); idx > 0 {
			owner = entry.Name[:idx]
		}
	}
	if owner == "" {
		return "", "", false
	}
	if _, after, found := strings.Cut(entry.Signature, "="); found {
		value = strings.Trim(strings.TrimSpace(after), `"`)
		if value != "" {
			return owner, value, true
		}
	}
	return "", "", false
}

func namedProtocolChildType(signature string) (string, bool) {
	typeExpr := signature
	if before, _, found := strings.Cut(signature, "`"); found {
		typeExpr = strings.TrimSpace(before)
	}
	typeExpr = strings.TrimSpace(typeExpr)
	typeExpr = strings.ReplaceAll(typeExpr, " ", "")
	for {
		switch {
		case strings.HasPrefix(typeExpr, "*"):
			typeExpr = strings.TrimPrefix(typeExpr, "*")
		case strings.HasPrefix(typeExpr, "[]"):
			typeExpr = strings.TrimPrefix(typeExpr, "[]")
		case strings.HasPrefix(typeExpr, "map[string]"):
			typeExpr = strings.TrimPrefix(typeExpr, "map[string]")
		case strings.HasPrefix(typeExpr, "Nullable["):
			inner := strings.TrimPrefix(typeExpr, "Nullable[")
			inner = strings.TrimSuffix(inner, "]")
			typeExpr = inner
		default:
			r, _ := utf8.DecodeRuneInString(typeExpr)
			if typeExpr == "" || !unicode.IsUpper(r) || strings.ContainsAny(typeExpr, "[]()*") {
				return "", false
			}
			switch typeExpr {
			case "string", "bool", "int", "int64", "uint64", "uint32", "float64", "byte", "JSONValue":
				return "", false
			default:
				return typeExpr, true
			}
		}
	}
}

func setNestedSet(dst map[string]map[string]struct{}, owner, key string) {
	if dst[owner] == nil {
		dst[owner] = map[string]struct{}{}
	}
	dst[owner][key] = struct{}{}
}

func setNestedMap(dst map[string]map[string]string, owner, key, value string) {
	if dst[owner] == nil {
		dst[owner] = map[string]string{}
	}
	dst[owner][key] = value
}

func writeStringSetMap(out *bytes.Buffer, name string, values map[string]map[string]struct{}) {
	fmt.Fprintf(out, "var %s = map[string]map[string]struct{}{\n", name)
	owners := make([]string, 0, len(values))
	for owner := range values {
		owners = append(owners, owner)
	}
	sort.Strings(owners)
	for _, owner := range owners {
		keys := make([]string, 0, len(values[owner]))
		for key := range values[owner] {
			keys = append(keys, key)
		}
		sort.Strings(keys)
		fmt.Fprintf(out, "\t%q: {\n", owner)
		for _, key := range keys {
			fmt.Fprintf(out, "\t\t%q: {},\n", key)
		}
		out.WriteString("\t},\n")
	}
	out.WriteString("}\n")
}

func writeStringStringMap(out *bytes.Buffer, name string, values map[string]map[string]string) {
	fmt.Fprintf(out, "var %s = map[string]map[string]string{\n", name)
	owners := make([]string, 0, len(values))
	for owner := range values {
		owners = append(owners, owner)
	}
	sort.Strings(owners)
	for _, owner := range owners {
		keys := make([]string, 0, len(values[owner]))
		for key := range values[owner] {
			keys = append(keys, key)
		}
		sort.Strings(keys)
		fmt.Fprintf(out, "\t%q: {\n", owner)
		for _, key := range keys {
			fmt.Fprintf(out, "\t\t%q: %q,\n", key, values[owner][key])
		}
		out.WriteString("\t},\n")
	}
	out.WriteString("}\n")
}
