package protocolgen

import (
	"fmt"
	"go/format"
	"regexp"
	"sort"
	"strings"
)

var (
	facadeTargetRE = regexp.MustCompile(`^([A-Za-z][A-Za-z0-9]*)\(\)\.([A-Za-z][A-Za-z0-9]*)$`)
)

type surfaceMethod struct {
	sourcePath   string
	accessor     string
	operation    string
	method       string
	methodConst  string
	paramsType   string
	responseType string
}

// GenerateSDKSurface derives the public facade from current manifest routing facts and generated protocol prerequisites.
// FacadeStatus is retained as manifest metadata for compatibility but does not authorize or suppress generation.
func GenerateSDKSurface(handwrittenDir string, manifest Manifest, methodConsts map[string]string, typeNames map[string]bool) ([]byte, error) {

	var methods []surfaceMethod
	seen := map[string]string{}
	for _, entry := range manifest.Entries {
		if entry.Direction != "client_to_server" || entry.Kind != "request" {
			continue
		}
		if strings.HasPrefix(entry.FacadeTarget, "internal.") {
			continue
		}
		match := facadeTargetRE.FindStringSubmatch(entry.FacadeTarget)
		if match == nil {
			return nil, &UnsupportedSchemaError{
				Path: facadeSourcePath(entry),
				Err:  fmt.Errorf("invalid generated facade target %q for method %q", entry.FacadeTarget, entry.Method),
			}
		}
		accessor, operation := match[1], match[2]
		methodConst := methodConsts[entry.Method]
		var missing []string
		if methodConst == "" {
			missing = append(missing, "method constant")
		}
		if entry.ParamsOrPayloadSchema != "" && !typeNames[entry.ParamsOrPayloadSchema] {
			missing = append(missing, "params type "+entry.ParamsOrPayloadSchema)
		}
		if entry.ResponseType == "" || !typeNames[entry.ResponseType] {
			if entry.ResponseType == "" {
				missing = append(missing, "response type <empty>")
			} else {
				missing = append(missing, "response type "+entry.ResponseType)
			}
		}
		if len(missing) > 0 {
			path := facadeSourcePath(entry)
			if (entry.ResponseType == "" || !typeNames[entry.ResponseType]) && entry.ResponseSchema != "" {
				path = entry.ResponseSchema
			}
			return nil, &UnsupportedSchemaError{
				Path: path,
				Err:  fmt.Errorf("facade method %q is missing current generated prerequisites: %s", entry.Method, strings.Join(missing, ", ")),
			}
		}
		key := accessor + "\x00" + operation
		if previous := seen[key]; previous != "" {
			return nil, &UnsupportedSchemaError{
				Path: facadeSourcePath(entry),
				Err:  fmt.Errorf("facade operation %s().%s maps both %q and %q", accessor, operation, previous, entry.Method),
			}
		}
		seen[key] = entry.Method
		methods = append(methods, surfaceMethod{
			sourcePath:   facadeSourcePath(entry),
			accessor:     accessor,
			operation:    operation,
			method:       entry.Method,
			methodConst:  methodConst,
			paramsType:   entry.ParamsOrPayloadSchema,
			responseType: entry.ResponseType,
		})
	}
	sort.Slice(methods, func(i, j int) bool {
		if methods[i].accessor != methods[j].accessor {
			return methods[i].accessor < methods[j].accessor
		}
		if methods[i].operation != methods[j].operation {
			return methods[i].operation < methods[j].operation
		}
		return methods[i].method < methods[j].method
	})

	var b strings.Builder
	b.WriteString("// Code generated by generatedcheck; DO NOT EDIT.\n\n")
	b.WriteString("package codexsdk\n\n")
	b.WriteString("import (\n")
	b.WriteString("\t\"context\"\n\n")
	b.WriteString("\t\"github.com/ronhuafeng/llm-go/codexsdk/protocolv2\"\n")
	b.WriteString(")\n\n")

	byAccessor := map[string][]surfaceMethod{}
	var accessors []string
	for _, method := range methods {
		if _, ok := byAccessor[method.accessor]; !ok {
			accessors = append(accessors, method.accessor)
		}
		byAccessor[method.accessor] = append(byAccessor[method.accessor], method)
	}
	knownSources := map[string][]string{}
	sort.Strings(accessors)
	for _, accessor := range accessors {
		for _, method := range byAccessor[accessor] {
			knownSources["sdk_surface.gen.go:type:"+accessor] = append(knownSources["sdk_surface.gen.go:type:"+accessor], method.sourcePath)
			knownSources["sdk_surface.gen.go:func:Client."+accessor] = append(knownSources["sdk_surface.gen.go:func:Client."+accessor], method.sourcePath)
		}
		b.WriteString("// " + accessor + " is an opaque generated facade for exact Codex operations.\n")
		b.WriteString("type " + accessor + " struct {\n")
		b.WriteString("\tclient *Client\n")
		b.WriteString("}\n\n")
		b.WriteString("func (c *Client) " + accessor + "() " + accessor + " {\n")
		b.WriteString("\treturn " + accessor + "{client: c}\n")
		b.WriteString("}\n\n")
	}
	for _, method := range methods {
		knownSources["sdk_surface.gen.go:func:"+method.accessor+"."+method.operation] = []string{method.sourcePath}
		if method.paramsType != "" {
			fmt.Fprintf(&b, "func (f %s) %s(ctx context.Context, params protocolv2.%s) (protocolv2.%s, error) {\n", method.accessor, method.operation, method.paramsType, method.responseType)
			fmt.Fprintf(&b, "\tvar response protocolv2.%s\n", method.responseType)
			fmt.Fprintf(&b, "\tif err := f.client.callProtocol(ctx, protocolv2.%s, params, &response); err != nil {\n", method.methodConst)
			fmt.Fprintf(&b, "\t\treturn protocolv2.%s{}, err\n", method.responseType)
			b.WriteString("\t}\n")
			b.WriteString("\treturn response, nil\n")
			b.WriteString("}\n\n")
			continue
		}
		fmt.Fprintf(&b, "func (f %s) %s(ctx context.Context) (protocolv2.%s, error) {\n", method.accessor, method.operation, method.responseType)
		fmt.Fprintf(&b, "\tvar response protocolv2.%s\n", method.responseType)
		fmt.Fprintf(&b, "\tif err := f.client.callProtocolNoParams(ctx, protocolv2.%s, &response); err != nil {\n", method.methodConst)
		fmt.Fprintf(&b, "\t\treturn protocolv2.%s{}, err\n", method.responseType)
		b.WriteString("\t}\n")
		b.WriteString("\treturn response, nil\n")
		b.WriteString("}\n\n")
	}

	formatted, err := format.Source([]byte(b.String()))
	if err != nil {
		return nil, &UnsupportedSchemaError{Path: "sdk_surface.gen.go", Err: fmt.Errorf("format generated sdk surface: %w", err)}
	}
	if err := validateGeneratedPackage("codexsdk", handwrittenDir, map[string][]byte{"sdk_surface.gen.go": formatted}, knownSources); err != nil {
		return nil, err
	}
	return formatted, nil
}

func facadeSourcePath(entry ManifestEntry) string {
	if entry.SourceSchema != "" {
		return entry.SourceSchema
	}
	return entry.Method
}
