package protocolsync

import (
	"fmt"
	"os"
	"regexp"
	"strings"
)

// PublishRequest publishes the current HEAD as a protected protocol-sync PR.
type PublishRequest struct {
	Repository, AppClientID, ExpectedHead, ExpectedBranch string
	API                                                   PublicationAPI
	Lookuper                                              RemoteLookuper
	RepoRoot                                              string
	BaseBranch                                            string
	TargetRef                                             string
	TargetKind                                            string
	TargetSHA                                             string
	Remote                                                string
	GitHubOutputPath                                      string
}

// Publish conditionally publishes the validated HEAD against the native state
// observed before generation. A pending PR is never reported as integrated.
func Publish(req PublishRequest) (url string, err error) {
	defer func() {
		if err != nil {
			_ = appendGitHubOutput(req.GitHubOutputPath, map[string]string{"outcome": OutcomeFailed, "stage": "publication", "failure_category": failureCategory(err)})
		}
	}()
	return publishCandidate(req)
}

func normalizeBranchRef(ref, remote string) string {
	ref = strings.TrimPrefix(ref, "refs/heads/")
	ref = strings.TrimPrefix(ref, "refs/remotes/"+remote+"/")
	ref = strings.TrimPrefix(ref, remote+"/")
	return ref
}

func syncBranchName(prefix, targetRef, targetSHA string) string {
	name := regexp.MustCompile(`^refs/(heads|tags)/`).ReplaceAllString(targetRef, "")
	if name == "" {
		name = targetSHA[:12]
	}
	name = regexp.MustCompile(`[^A-Za-z0-9._-]+`).ReplaceAllString(name, "-")
	name = strings.Trim(name, "-.")
	if name == "" {
		name = targetSHA[:12]
	}
	if len(name) > 64 {
		name = name[:64]
	}
	return strings.TrimRight(prefix, "-/") + "-" + name + "-" + targetSHA[:12]
}

func parseSyncMetadata(body string) map[string]string {
	start := strings.Index(body, "<!-- codexsdk-upstream-sync")
	if start < 0 {
		return map[string]string{}
	}
	end := strings.Index(body[start:], "-->")
	if end < 0 {
		return map[string]string{}
	}
	parsed := map[string]string{}
	for _, line := range strings.Split(body[start:start+end], "\n") {
		key, value, ok := strings.Cut(line, ":")
		if !ok {
			continue
		}
		key = strings.TrimSpace(key)
		switch key {
		case "upstream_ref", "upstream_ref_kind", "upstream_commit", "sync_commit", "base_branch":
			parsed[key] = strings.TrimSpace(value)
		}
	}
	return parsed
}

func publicationTitle(ref string) string { return "Sync Codex protocol baseline to " + ref }

func publicationBody(landRef, targetRef, targetKind, targetSHA, syncCommit string) string {
	return fmt.Sprintf(`<!-- codexsdk-upstream-sync
upstream_ref: %s
upstream_ref_kind: %s
upstream_commit: %s
sync_commit: %s
base_branch: %s
-->

Automated upstream protocol sync.

## Description

This PR advances the checked-in protocol baseline for the selected upstream target, regenerates deterministic SDK artifacts, includes any one-run handwritten updates required by real drift, and publishes only after native checks passed.

It does not merge itself, tag, or bypass branch protection.

## Sync Metadata

- Upstream ref: `+"`%s`"+`
- Upstream ref kind: `+"`%s`"+`
- Upstream commit: `+"`%s`"+`
- Sync commit: `+"`%s`"+`
- Base branch: `+"`%s`"+`

This PR was generated by the upstream protocol sync workflow. It stops at the protected PR boundary and does not tag or bypass branch protection. Merge should happen only after branch protection and the required `+"`PR verification`"+` check accept this head commit.
`, targetRef, targetKind, targetSHA, syncCommit, landRef, targetRef, targetKind, targetSHA, syncCommit, landRef)
}

func appendGitHubOutput(path string, values map[string]string) error {
	if path == "" {
		return nil
	}
	f, err := os.OpenFile(path, os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0o644)
	if err != nil {
		return err
	}
	defer f.Close()
	for key, value := range values {
		if _, err := fmt.Fprintf(f, "%s=%s\n", key, value); err != nil {
			return err
		}
	}
	return nil
}
