package protocolgen

import (
	"bytes"
	"fmt"
	"go/format"
	"sort"
	"strings"
	"unicode"
)

func GenerateMethodRegistry(manifest Manifest) ([]byte, error) {
	entries := append([]ManifestEntry(nil), manifest.Entries...)
	sort.Slice(entries, func(i, j int) bool {
		return entries[i].Method < entries[j].Method
	})

	var out bytes.Buffer
	out.WriteString("// Code generated by protocolv2gen; DO NOT EDIT.\n")
	out.WriteString("package protocolv2\n\n")
	out.WriteString("type MethodDirection string\n\n")
	out.WriteString("const (\n")
	out.WriteString("\tMethodDirectionClientToServer MethodDirection = \"client_to_server\"\n")
	out.WriteString("\tMethodDirectionServerToClient MethodDirection = \"server_to_client\"\n")
	out.WriteString(")\n\n")
	out.WriteString("type MethodKind string\n\n")
	out.WriteString("const (\n")
	out.WriteString("\tMethodKindRequest MethodKind = \"request\"\n")
	out.WriteString("\tMethodKindNotification MethodKind = \"notification\"\n")
	out.WriteString(")\n\n")
	out.WriteString("type MethodStability string\n\n")
	out.WriteString("const (\n")
	out.WriteString("\tMethodStabilityStable MethodStability = \"stable\"\n")
	out.WriteString("\tMethodStabilityExperimental MethodStability = \"experimental\"\n")
	out.WriteString(")\n\n")
	out.WriteString("type ResponseSchemaStatus string\n\n")
	out.WriteString("const (\n")
	out.WriteString("\tResponseSchemaStatusDeclared ResponseSchemaStatus = \"declared\"\n")
	out.WriteString("\tResponseSchemaStatusNotApplicable ResponseSchemaStatus = \"not_applicable\"\n")
	out.WriteString(")\n\n")
	out.WriteString("type MethodInfo struct {\n")
	out.WriteString("\tMethod string\n")
	out.WriteString("\tDirection MethodDirection\n")
	out.WriteString("\tKind MethodKind\n")
	out.WriteString("\tFamily string\n")
	out.WriteString("\tParamsOrPayloadSchema string\n")
	out.WriteString("\tResponseSchema string\n")
	out.WriteString("\tResponseSchemaStatus ResponseSchemaStatus\n")
	out.WriteString("\tFacadeTarget string\n")
	out.WriteString("\tStability MethodStability\n")
	out.WriteString("}\n\n")
	out.WriteString("const (\n")
	for _, entry := range entries {
		fmt.Fprintf(&out, "\t%s = %q\n", methodConstName(entry.Method), entry.Method)
	}
	out.WriteString(")\n\n")
	out.WriteString("var methodRegistry = map[string]MethodInfo{\n")
	for _, entry := range entries {
		fmt.Fprintf(&out, "\t%s: {\n", methodConstName(entry.Method))
		fmt.Fprintf(&out, "\t\tMethod: %s,\n", methodConstName(entry.Method))
		fmt.Fprintf(&out, "\t\tDirection: %s,\n", directionConst(entry.Direction))
		fmt.Fprintf(&out, "\t\tKind: %s,\n", kindConst(entry.Kind))
		fmt.Fprintf(&out, "\t\tFamily: %q,\n", entry.Family)
		fmt.Fprintf(&out, "\t\tParamsOrPayloadSchema: %q,\n", entry.ParamsOrPayloadSchema)
		fmt.Fprintf(&out, "\t\tResponseSchema: %q,\n", entry.ResponseSchema)
		fmt.Fprintf(&out, "\t\tResponseSchemaStatus: %s,\n", responseSchemaStatusConst(entry.ResponseSchemaStatus))
		fmt.Fprintf(&out, "\t\tFacadeTarget: %q,\n", entry.FacadeTarget)
		fmt.Fprintf(&out, "\t\tStability: %s,\n", stabilityConst(entry.Stability))
		out.WriteString("\t},\n")
	}
	out.WriteString("}\n\n")
	out.WriteString("func LookupMethod(method string) (MethodInfo, bool) {\n")
	out.WriteString("\tinfo, ok := methodRegistry[method]\n")
	out.WriteString("\treturn info, ok\n")
	out.WriteString("}\n\n")
	out.WriteString("func AllMethods() []MethodInfo {\n")
	out.WriteString("\tmethods := make([]MethodInfo, 0, len(methodRegistry))\n")
	out.WriteString("\tfor _, info := range methodRegistry {\n")
	out.WriteString("\t\tmethods = append(methods, info)\n")
	out.WriteString("\t}\n")
	out.WriteString("\tsortMethodInfo(methods)\n")
	out.WriteString("\treturn methods\n")
	out.WriteString("}\n\n")
	out.WriteString("func sortMethodInfo(methods []MethodInfo) {\n")
	out.WriteString("\tfor i := 1; i < len(methods); i++ {\n")
	out.WriteString("\t\tfor j := i; j > 0 && methods[j-1].Method > methods[j].Method; j-- {\n")
	out.WriteString("\t\t\tmethods[j-1], methods[j] = methods[j], methods[j-1]\n")
	out.WriteString("\t\t}\n")
	out.WriteString("\t}\n")
	out.WriteString("}\n")

	formatted, err := format.Source(out.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format generated method registry: %w", err)
	}
	return formatted, nil
}

func methodConstName(method string) string {
	parts := identifierParts(method)
	if len(parts) == 0 {
		return "MethodUnknown"
	}
	var b strings.Builder
	b.WriteString("Method")
	for _, part := range parts {
		b.WriteString(goNamePart(part))
	}
	return b.String()
}

func identifierParts(text string) []string {
	var parts []string
	var current []rune
	flush := func() {
		if len(current) == 0 {
			return
		}
		parts = append(parts, string(current))
		current = current[:0]
	}
	for _, r := range text {
		if !unicode.IsLetter(r) && !unicode.IsDigit(r) {
			flush()
			continue
		}
		if len(current) > 0 {
			prev := current[len(current)-1]
			if unicode.IsDigit(r) != unicode.IsDigit(prev) || unicode.IsUpper(r) && unicode.IsLower(prev) {
				flush()
			}
		}
		current = append(current, r)
	}
	flush()
	return parts
}

func goNamePart(part string) string {
	switch strings.ToLower(part) {
	case "api":
		return "API"
	case "app":
		return "App"
	case "auth":
		return "Auth"
	case "chatgpt":
		return "ChatGPT"
	case "config":
		return "Config"
	case "cwd":
		return "CWD"
	case "cwds":
		return "CWDs"
	case "fs":
		return "FS"
	case "id":
		return "ID"
	case "ids":
		return "IDs"
	case "http":
		return "HTTP"
	case "json":
		return "JSON"
	case "mcp":
		return "MCP"
	case "ms":
		return "MS"
	case "oauth":
		return "OAuth"
	case "pty":
		return "PTY"
	case "sdp":
		return "SDP"
	case "sha":
		return "SHA"
	case "ui":
		return "UI"
	case "uri":
		return "URI"
	case "uris":
		return "URIs"
	case "url":
		return "URL"
	case "urls":
		return "URLs"
	default:
		return strings.ToUpper(part[:1]) + part[1:]
	}
}

func directionConst(direction string) string {
	switch direction {
	case "client_to_server":
		return "MethodDirectionClientToServer"
	case "server_to_client":
		return "MethodDirectionServerToClient"
	default:
		return fmt.Sprintf("MethodDirection(%q)", direction)
	}
}

func kindConst(kind string) string {
	switch kind {
	case "request":
		return "MethodKindRequest"
	case "notification":
		return "MethodKindNotification"
	default:
		return fmt.Sprintf("MethodKind(%q)", kind)
	}
}

func stabilityConst(stability string) string {
	switch stability {
	case "stable":
		return "MethodStabilityStable"
	case "experimental":
		return "MethodStabilityExperimental"
	default:
		return fmt.Sprintf("MethodStability(%q)", stability)
	}
}

func responseSchemaStatusConst(status string) string {
	switch status {
	case "declared":
		return "ResponseSchemaStatusDeclared"
	case "not_applicable":
		return "ResponseSchemaStatusNotApplicable"
	default:
		return fmt.Sprintf("ResponseSchemaStatus(%q)", status)
	}
}
